import type { BlogPost } from "@/lib/blog";

export const AI_POSTS_1: BlogPost[] = [
  {
    slug: "ai-voor-mkb-waar-begin-je-echt",
    image: "/blog/ai-content.jpg",
    title: "AI voor het MKB: waar begin je echt?",
    date: "2025-10-06",
    excerpt: "Iedereen roept dat je iets met AI moet. Maar waarmee dan? Hier is hoe ik het zou aanpakken als ik een MKB-bedrijf in de Kempen had.",
    readTime: "5 min",
    category: "AI voor MKB",
    content: [
      { type: "intro", text: "Bijna elke ondernemer die ik in de Kempen spreek, voelt de druk. Je hoort dat AI alles gaat veranderen, maar niemand vertelt je waar je morgen moet beginnen. Mijn antwoord is simpel: niet bij de hype, maar bij je eigen werkweek." },
      { type: "h2", text: "Begin niet bij de tool, begin bij je tijd" },
      { type: "p", text: "De meeste mensen kopen eerst een tool en zoeken daarna een probleem. Dat is de verkeerde volgorde. Pak een vel papier en schrijf op welke drie taken jou elke week het meeste tijd kosten en het minste energie geven. Dat is je startpunt." },
      { type: "p", text: "Voor de een is dat offertes typen, voor de ander mailtjes beantwoorden of facturen rondsturen. Het maakt niet uit wat het is, als het maar terugkomt en als het maar saai is. Saai en herhalend is precies waar AI goed in is." },
      { type: "h2", text: "Kies drie processen en laat daar een tool op los" },
      { type: "ul", items: ["Schrijf de drie tijdvreters op die elke week terugkomen", "Kies per proces een concrete tool, niet een vaag plan", "Test twee weken en meet of het echt sneller gaat", "Houd wat werkt, gooi de rest weg zonder schuldgevoel"] },
      { type: "p", text: "Ik heb dit zelf gedaan met mijn eigen administratie. Ik bouwde een systeem dat mijn uren, facturen en BTW grotendeels automatisch verwerkt. Niet omdat het indrukwekkend klinkt, maar omdat ik die avonden met spreadsheets spuugzat was." },
      { type: "quote", text: "Begin klein, met een proces dat je echt irriteert. Eén werkende oplossing overtuigt je meer dan tien blogposts over de toekomst." },
      { type: "h2", text: "Verwacht geen wonder, verwacht ademruimte" },
      { type: "p", text: "AI gaat je bedrijf niet runnen. Het neemt een stuk routinewerk over zodat jij tijd overhoudt voor de dingen die er wel toe doen: klanten spreken, beslissingen nemen, je vak uitoefenen. Dat is geen magie, dat is gewoon slim werken." },
      { type: "infographic", infographic: "ai-volwassenheid" },
      { type: "cta", text: "Wil je weten welke drie processen in jouw bedrijf het eerst geschikt zijn? Doe de gratis AI-quickscan op mijn site." },
    ],
  },
  {
    slug: "chatgpt-claude-gemini-welk-taalmodel-past-bij-jouw-bedrijf",
    image: "/blog/inzichten.jpg",
    title: "ChatGPT, Claude of Gemini: welk taalmodel past bij jouw bedrijf?",
    date: "2025-10-13",
    excerpt: "Drie grote namen, drie sterke modellen. Welke je kiest hangt af van wat je ermee doet. Een nuchtere keuzehulp zonder kampvuurverhalen.",
    readTime: "6 min",
    category: "Taalmodellen",
    content: [
      { type: "intro", text: "Ondernemers vragen me vaak welk AI-model het beste is. Dat is de verkeerde vraag. De goede vraag is: welk model past bij wat jij elke dag doet? Ik gebruik ze alle drie, en ze zijn alle drie ergens goed in." },
      { type: "h2", text: "ChatGPT: de allrounder om mee te starten" },
      { type: "p", text: "Als je nog nooit met AI hebt gewerkt, is ChatGPT van OpenAI een logische eerste stap. Het kan veel, het is laagdrempelig en er zijn ontzettend veel handleidingen te vinden. Voor brainstormen, snelle teksten en algemene vragen werkt het prima." },
      { type: "h2", text: "Claude: mijn keuze voor serieus schrijfwerk" },
      { type: "p", text: "Claude van Anthropic is waar ik naartoe ben gegaan voor langere teksten en nuance. Het houdt toon beter vast, gokt minder en levert tekst die ik minder hoef te herschrijven. Voor blogposts, klantmails en documenten is dit mijn werkpaard." },
      { type: "h2", text: "Gemini: sterk in het Google-ecosysteem" },
      { type: "p", text: "Gemini van Google leunt op alles wat je al in Gmail, Docs en Sheets doet. Werk je veel in die omgeving, dan voelt Gemini als een natuurlijke uitbreiding. Het is ook handig bij het verwerken van grote hoeveelheden informatie in een keer." },
      { type: "h2", text: "Zo kies je in de praktijk" },
      { type: "ul", items: ["Net begonnen en alles uitproberen: ChatGPT", "Veel schrijfwerk waar toon en nuance tellen: Claude", "Diep in Google Workspace: Gemini", "Twijfel je: neem een betaald abonnement op een en gebruik dat een maand serieus"] },
      { type: "quote", text: "Het beste model is niet het slimste op papier. Het is het model dat jij daadwerkelijk elke dag opent." },
      { type: "p", text: "Mijn advies: kies er een, gebruik het een maand intensief en oordeel daarna pas. Springen tussen drie modellen omdat iemand op LinkedIn riep dat een ander beter is, kost je vooral tijd. De verschillen zijn echt, maar ze worden online flink overdreven." },
      { type: "infographic", infographic: "model-vergelijking" },
      { type: "cta", text: "Niet zeker welk model bij jouw werk past? Doe de AI-quickscan, dan kijken we samen naar je situatie." },
    ],
  },
  {
    slug: "5-fouten-die-ondernemers-maken-met-chatgpt",
    image: "/blog/ai-camera.jpg",
    title: "De 5 fouten die ondernemers maken met ChatGPT",
    date: "2025-10-20",
    excerpt: "AI werkt niet voor je omdat je het verkeerd gebruikt, niet omdat het niet kan. Vijf valkuilen die ik telkens terugzie, met de fix erbij.",
    readTime: "5 min",
    category: "AI-tools",
    content: [
      { type: "intro", text: "Veel ondernemers proberen ChatGPT een keer, krijgen een matig antwoord en concluderen dat AI niks voor hen is. Negen van de tien keer ligt het niet aan het model, maar aan hoe het gevraagd wordt. Dit zijn de fouten die ik het vaakst zie." },
      { type: "h2", text: "Fout 1: te vaag vragen" },
      { type: "p", text: "Schrijf een tekst over mijn bedrijf levert een grijze, nietszeggende tekst op. Logisch, want het model weet niks van jou. Geef context: wat doe je, voor wie, in welke toon, en wat moet de lezer daarna doen. Hoe specifieker je vraag, hoe bruikbaarder het antwoord." },
      { type: "h2", text: "Fout 2: het eerste antwoord meteen accepteren" },
      { type: "p", text: "Het eerste antwoord is zelden het beste. Het is een startpunt. Zeg gerust: maak het korter, schrap de marketingtaal, schrijf het zoals een Brabander zou praten. Doorvragen is geen omweg, het is de manier waarop het werkt." },
      { type: "h2", text: "Fout 3: vertrouwelijke gegevens erin gooien" },
      { type: "p", text: "Plak geen klantdossiers, wachtwoorden of gevoelige cijfers in een gratis chatvenster. Behandel het als een open ruimte. Wil je met bedrijfsdata werken, kies dan een zakelijke variant met de juiste afspraken over je gegevens." },
      { type: "h2", text: "Fout 4: blind vertrouwen op de feiten" },
      { type: "ul", items: ["Een taalmodel kan overtuigend onzin vertellen", "Het verzint soms bronnen, jaartallen of citaten", "Controleer alles wat als feit telt altijd zelf", "Gebruik het voor concept en structuur, niet als waarheidsmachine"] },
      { type: "quote", text: "AI is een ijzersterke assistent en een waardeloze baas. Jij blijft degene die controleert en beslist." },
      { type: "h2", text: "Fout 5: stoppen na een week" },
      { type: "p", text: "Net als met elk gereedschap moet je het leren gebruiken. De ondernemers die er echt iets aan hebben, zijn niet de slimste, het zijn degenen die het vol bleven gebruiken tot het natuurlijk aanvoelde. Geef jezelf een maand, niet een middag." },
      { type: "cta", text: "Wil je leren hoe je AI echt voor je laat werken? Stuur me een bericht via de site." },
    ],
  },
  {
    slug: "10-ai-tools-die-elk-mkb-bedrijf-moet-kennen",
    image: "/blog/ai-content.jpg",
    title: "10 AI-tools die elk MKB-bedrijf in 2025 moet kennen",
    date: "2025-10-27",
    excerpt: "Geen lijst van honderd tools die je toch nooit opent. Tien categorieen die echt iets opleveren voor een gewoon bedrijf in de Kempen.",
    readTime: "6 min",
    category: "AI-tools",
    content: [
      { type: "intro", text: "Er verschijnen elke week nieuwe AI-tools en de meeste heb je niet nodig. In plaats van een eindeloze lijst geef ik je tien categorieen waar een MKB-bedrijf echt iets aan heeft. Kies per categorie een tool en je bent verder dan de meesten." },
      { type: "h2", text: "Schrijven en communicatie" },
      { type: "ul", items: ["Een taalmodel zoals Claude of ChatGPT voor mails, offertes en teksten", "Een grammatica- en taalhulp voor foutloze klantcommunicatie", "Een vertaaltool voor klanten over de grens of Engelstalige leveranciers"] },
      { type: "h2", text: "Beeld en video" },
      { type: "ul", items: ["Een beeldgenerator voor snelle visuals bij social posts", "Een tool die automatisch ondertitels op je video plakt", "Een achtergrond-verwijderaar voor nette productfotos"] },
      { type: "h2", text: "Werk en administratie" },
      { type: "ul", items: ["Een notulen-tool die je gesprekken samenvat", "Een planningstool die mailtjes en afspraken voor je sorteert", "Een chatbot die veelgestelde vragen van klanten afvangt", "Een automatiseringstool die je losse programmas aan elkaar knoopt"] },
      { type: "p", text: "Een paar van deze categorieen heb ik zelf ingevuld met maatwerk. Voor een restaurant bouwde ik bijvoorbeeld een chatbot die zelf tafels reserveert. Dat valt onder die laatste rij, maar dan helemaal toegespitst op een specifieke zaak." },
      { type: "quote", text: "Tien tools tegelijk invoeren werkt niet. Eentje per maand goed leren gebruiken wel." },
      { type: "h2", text: "Hoe je hiermee start zonder te verzuipen" },
      { type: "p", text: "Pak deze lijst niet als boodschappenlijstje. Kies de twee categorieen die jouw grootste ergernis raken en begin daar. Werkt het na een paar weken, dan pak je de volgende. Zo bouw je rustig een werkwijze op in plaats van een berg abonnementen die je nooit opent." },
      { type: "cta", text: "Geen idee welke tools bij jouw bedrijf passen? De AI-quickscan op mijn site geeft je een eerste richting." },
    ],
  },
  {
    slug: "wat-is-een-goede-ai-prompt-7-voorbeelden",
    image: "/blog/inzichten.jpg",
    title: "Wat is een goede AI-prompt? (7 voorbeelden)",
    date: "2025-11-03",
    excerpt: "Een goede prompt is geen toverspreuk, het is gewoon een duidelijke opdracht. Met deze formule en zeven voorbeelden krijg je meteen betere antwoorden.",
    readTime: "5 min",
    category: "AI-tools",
    content: [
      { type: "intro", text: "De kwaliteit van wat AI teruggeeft, hangt vooral af van hoe je het vraagt. Slechte vraag, slecht antwoord. Het goede nieuws: je hoeft geen techneut te zijn om goede prompts te schrijven. Je hebt alleen een simpele formule nodig." },
      { type: "h2", text: "De formule: rol, context, format" },
      { type: "p", text: "Een sterke prompt bestaat uit drie delen. Eerst de rol: wie moet het model zijn. Dan de context: wat is de situatie en voor wie. En tot slot het format: in welke vorm wil je het antwoord. Combineer die drie en je krijgt meteen bruikbaardere tekst." },
      { type: "h2", text: "Zeven voorbeelden die je direct kunt gebruiken" },
      { type: "ul", items: ["Je bent een verkoper. Schrijf een korte offerte-mail voor een klant die twijfelt over de prijs. Maximaal 100 woorden, vriendelijk en zeker.", "Je bent tekstschrijver. Herschrijf deze alinea zodat een 12-jarige hem begrijpt. Geen jargon.", "Je bent mijn assistent. Vat dit gesprek samen in vijf bullets met de afspraken die we maakten.", "Je bent recruiter. Maak een vacaturetekst voor een monteur in de Kempen, nuchtere toon, geen holle frases.", "Je bent marketeer. Bedenk vijf onderwerpen voor social posts voor een lokaal bouwbedrijf.", "Je bent redacteur. Controleer deze klantmail op fouten en een te formele toon.", "Je bent ondernemer. Bedenk drie tegenargumenten op mijn aanbod zodat ik me kan voorbereiden."] },
      { type: "quote", text: "Praat tegen AI zoals tegen een nieuwe medewerker. Niemand levert goed werk op een vage opdracht." },
      { type: "h2", text: "Waarom dit werkt" },
      { type: "p", text: "Door een rol te geven, kiest het model de juiste toon. Door context te geven, snapt het de situatie. Door een format te vragen, krijg je iets bruikbaars in plaats van een lap tekst. Het lijkt klein, maar het verschil is enorm." },
      { type: "p", text: "Bewaar je beste prompts ergens in een notitie. Na een tijdje heb je een eigen setje dat steeds opnieuw werkt voor jouw bedrijf. Dat scheelt je elke keer dat je opnieuw moet uitleggen wat je wilt." },
      { type: "infographic", infographic: "prompt-formule" },
      { type: "cta", text: "Wil je een setje prompts op maat voor jouw bedrijf? Neem contact op via de site." },
    ],
  },
  {
    slug: "hoeveel-tijd-bespaart-ai-je-echt-een-eerlijke-rekensom",
    image: "/blog/ai-camera.jpg",
    title: "Hoeveel tijd bespaart AI je echt? Een eerlijke rekensom",
    date: "2025-11-10",
    excerpt: "Geen beloftes van tien keer sneller. Wel een nuchtere rekensom over wat AI realistisch oplevert op het werk dat zich herhaalt.",
    readTime: "5 min",
    category: "AI voor MKB",
    content: [
      { type: "intro", text: "Online lees je dat AI je tien keer productiever maakt. Dat klopt niet, en zulke beloftes maken me wantrouwig. Maar er valt wel echt tijd te winnen. Laten we het gewoon eens uitrekenen, nuchter en zonder verkooppraatje." },
      { type: "h2", text: "Waar de winst echt zit" },
      { type: "p", text: "AI is sterk op repeterend werk: tekst opstellen, samenvatten, sorteren, herschrijven. Op dat soort taken kun je in mijn ervaring een flink deel van die tijd terugwinnen, vaak rond een kwart tot een derde. Niet op alles, en niet op het denkwerk, maar op de routine wel. Hoeveel precies verschilt per bedrijf." },
      { type: "h2", text: "Een voorbeeld uit de praktijk" },
      { type: "p", text: "Stel je besteedt 6 uur per week aan mails, offertes en kleine teksten. Met AI als hulp doe je dat realistisch in ongeveer 4 uur. Dat is 2 uur per week, oftewel bijna een hele werkdag per maand. Niet spectaculair, wel substantieel." },
      { type: "ul", items: ["6 uur repeterend schrijfwerk per week", "Ongeveer 30 procent sneller met AI als assistent", "Dat is bijna 2 uur winst per week", "Op jaarbasis tikt dat flink aan (dit is een voorbeeld, geen belofte)"] },
      { type: "infographic", infographic: "tijdwinst" },
      { type: "h2", text: "Waar je geen tijd wint" },
      { type: "p", text: "Het denkwerk, de relatie met je klant, de beslissingen: daar verandert weinig. AI maakt het concept, jij maakt het af. Wie verwacht dat het bedrijf zichzelf gaat runnen, komt bedrogen uit. Wie het inzet op de juiste taken, krijgt ademruimte." },
      { type: "quote", text: "AI haalt niet je werk weg, het haalt het saaie deel van je werk weg. Dat is precies het deel dat je tijd vrat." },
      { type: "h2", text: "Mijn eigen rekensom" },
      { type: "p", text: "Toen ik mijn administratie deels automatiseerde met een eigen systeem voor uren, facturen en BTW, won ik geen uren per dag. Maar de avonden dat ik met spreadsheets bezig was, zijn grotendeels verdwenen. Dat is voor mij meer waard dan welk percentage dan ook." },
      { type: "cta", text: "Benieuwd hoeveel tijd jij realistisch kunt winnen? Doe de AI-quickscan op mijn site." },
    ],
  },
  {
    slug: "grok-4-1-en-gemini-3-de-ai-race-versnelt",
    image: "/blog/inzichten.jpg",
    title: "Grok 4.1 en Gemini 3 in een week: de AI-race versnelt",
    date: "2025-11-17",
    excerpt: "Twee grote modellen in een week tijd. Wat betekent die release-golf voor jou als ondernemer, en wat juist niet?",
    readTime: "5 min",
    category: "AI-nieuws",
    content: [
      { type: "intro", text: "De afgelopen week kwamen Grok 4.1 van xAI en Gemini 3 van Google vrijwel achter elkaar uit. Voor wie het volgt voelt het als een wapenwedloop. Voor wie gewoon een bedrijf runt, is de belangrijkste vraag: moet ik hier iets mee?" },
      { type: "h2", text: "Wat er gebeurde" },
      { type: "p", text: "In korte tijd lanceerden twee grote spelers een nieuwe versie van hun model. Beide claimen betere prestaties op redeneren, schrijven en het verwerken van grote hoeveelheden informatie. De benchmarks gaan omhoog, dat is de rode draad van dit jaar." },
      { type: "h2", text: "Wat dit voor jou betekent" },
      { type: "p", text: "Op de korte termijn: weinig spannends. De modellen die je vandaag gebruikt, werken morgen nog steeds. Je hoeft niet bij elke release over te stappen. Sterker nog, dat zou je vooral tijd en focus kosten zonder dat je klant er iets van merkt." },
      { type: "ul", items: ["Nieuwe versies zijn meestal verbeteringen, geen breuken", "De winst voor MKB zit in het toepassen, niet in het nieuwste model", "Wachten een paar weken en de stof laten neerdalen is prima", "Een stabiele werkwijze is meer waard dan altijd het nieuwste"] },
      { type: "quote", text: "De modellen worden sneller beter dan de meeste bedrijven ze kunnen bijhouden. Dat is geen probleem, dat is een geruststelling." },
      { type: "h2", text: "Waarom de versnelling toch goed nieuws is" },
      { type: "p", text: "Dat de grote spelers elkaar opjagen, betekent dat de tools die jij gebruikt steeds beter en vaak goedkoper worden, zonder dat jij iets hoeft te doen. Je hoeft niet vooraan te staan in de race. Je hoeft alleen de winst op te pikken die vanzelf naar beneden zakt." },
      { type: "p", text: "Mijn advies blijft hetzelfde als een jaar geleden: kies een model dat werkt, gebruik het serieus, en kijk een paar keer per jaar of er iets fundamenteel beters is. De rest is ruis." },
      { type: "cta", text: "Wil je weten welk model nu het beste bij jouw bedrijf past, los van de hype? Neem contact op." },
    ],
  },
  {
    slug: "claude-opus-4-5-waarom-dit-model-anders-schrijft",
    image: "/blog/ai-content.jpg",
    title: "Claude Opus 4.5 is er: waarom dit model anders schrijft",
    date: "2025-11-24",
    excerpt: "Claude Opus 4.5 valt vooral op door nuance en lange teksten die niet uit elkaar vallen. Een eerlijke kijk op wat dat voor jou betekent.",
    readTime: "6 min",
    category: "AI-nieuws",
    content: [
      { type: "intro", text: "Anthropic bracht Claude Opus 4.5 uit, en als iemand die veel met deze modellen schrijft viel me direct iets op. Het gaat hier niet om een hoger getal op een benchmark. Het gaat om de manier waarop dit model met taal omgaat." },
      { type: "h2", text: "Nuance in plaats van zekerheid" },
      { type: "p", text: "Veel modellen klinken altijd even stellig, ook als ze het mis hebben. Opus 4.5 durft genuanceerder te zijn: het geeft eerder aan dat iets afhangt van de situatie, in plaats van een vlot maar fout antwoord. Voor zakelijk gebruik is dat precies wat je wilt." },
      { type: "h2", text: "Lange teksten die niet uit elkaar vallen" },
      { type: "p", text: "Het grootste verschil zit voor mij in langere stukken. Waar andere modellen halverwege de toon kwijtraken of zichzelf gaan herhalen, houdt dit model een rode draad vast. Een rapport, een lange klantmail of een uitgebreid voorstel blijft van begin tot eind kloppen." },
      { type: "ul", items: ["Houdt toon en stijl vast over lange teksten", "Herhaalt zichzelf minder snel", "Durft te nuanceren in plaats van altijd stellig te zijn", "Levert tekst die ik minder hoef te herschrijven"] },
      { type: "quote", text: "Het verschil zit niet in wat het model weet, maar in hoe het zich uitdrukt. Voor schrijfwerk is dat het hele spel." },
      { type: "h2", text: "Wat dit voor het MKB betekent" },
      { type: "p", text: "Voor de meeste ondernemers is dit geen reden om vannacht iets te veranderen. Maar als schrijven een groot deel van je werk is, offertes, klantcommunicatie, voorstellen, dan merk je dit soort verbeteringen wel degelijk in de praktijk. Minder herschrijven betekent minder tijd kwijt." },
      { type: "p", text: "Ik blijf nuchter over benchmarkcijfers, want die zeggen weinig over jouw dagelijkse werk. Wat telt, is of de tekst die eruit komt minder bijwerk kost. Bij dit model is dat voor mijn schrijfwerk merkbaar het geval." },
      { type: "cta", text: "Werk je veel met teksten en wil je weten of dit voor jou loont? Stuur me een bericht via de site." },
    ],
  },
  {
    slug: "van-chatgpt-naar-claude-waarom-ik-overstapte-voor-schrijfwerk",
    image: "/blog/ai-camera.jpg",
    title: "Van ChatGPT naar Claude: waarom ik overstapte voor schrijfwerk",
    date: "2025-12-01",
    excerpt: "Ik begon net als iedereen met ChatGPT. Voor schrijfwerk ben ik overgestapt naar Claude. Hier is mijn eerlijke verhaal, met de min- en pluspunten.",
    readTime: "6 min",
    category: "Taalmodellen",
    content: [
      { type: "intro", text: "Ik ben geen fanboy van een merk. Ik gebruik wat werkt. Voor schrijfwerk ben ik in de loop van dit jaar van ChatGPT naar Claude gegaan, en mensen vragen me regelmatig waarom. Dit is het eerlijke verhaal, met de nadelen erbij." },
      { type: "h2", text: "Waar het begon" },
      { type: "p", text: "Net als bijna iedereen startte ik met ChatGPT. Het is laagdrempelig, het kan veel en je vindt overal uitleg. Voor brainstormen en snelle teksten gebruik ik het nog steeds met plezier. Niets mis mee, het deed lang prima dienst." },
      { type: "h2", text: "Waarom ik schoof voor schrijfwerk" },
      { type: "p", text: "Bij langere teksten merkte ik dat ik veel bleef herschrijven. De toon klopte net niet, het werd te wollig of het ging halverwege zweven. Toen ik Claude serieus ging gebruiken voor blogs en klantmails, was er meteen minder bijwerk. De tekst stond dichter bij hoe ik zelf praat." },
      { type: "ul", items: ["Claude houdt toon en nuance beter vast in lange teksten", "Ik herschrijf minder, dat scheelt me echt tijd", "Het gokt minder en geeft eerder aan als iets onzeker is", "Voor structuur en redeneren bevalt het me sterk"] },
      { type: "quote", text: "Een tool is geen religie. Gebruik er twee als dat beter werkt en kies per klus de juiste." },
      { type: "h2", text: "De eerlijke nadelen" },
      { type: "p", text: "Het is geen zwart-wit verhaal. ChatGPT heeft meer kant-en-klare extra functies en een groter ecosysteem eromheen. Voor sommige snelle taken pak ik nog steeds ChatGPT. En als je net begint, is de overvloed aan uitleg bij ChatGPT een echt voordeel." },
      { type: "p", text: "Wat ik vooral wil zeggen: laat je niet gek maken door wie waar de beste in is. Ik gebruik allebei. Het zwaardere schrijfwerk gaat naar Claude, het snelle werk vaak nog naar ChatGPT. Kies op basis van je eigen werk, niet op basis van een ranglijst." },
      { type: "cta", text: "Twijfel je welk model bij jouw schrijfwerk past? Doe de AI-quickscan, dan denk ik met je mee." },
    ],
  },
  {
    slug: "ai-automatisering-wat-kun-je-nu-echt-bouwen-voor-je-bedrijf",
    image: "/blog/ai-content.jpg",
    title: "AI-automatisering: wat kun je nu echt bouwen voor je bedrijf?",
    date: "2025-12-08",
    excerpt: "Geen toekomstmuziek, maar concrete mini-workflows die je vandaag al kunt bouwen: van offerte tot intake tot online betaling.",
    readTime: "7 min",
    category: "Automatisering",
    content: [
      { type: "intro", text: "Automatisering klinkt voor veel ondernemers groot en duur. Dat hoeft het niet te zijn. Je hoeft niet je hele bedrijf om te bouwen. Je begint met een paar kleine workflows die elke dag terugkomen. Hier zijn er een paar die ik echt heb gebouwd of zou bouwen." },
      { type: "h2", text: "Offerte-workflow" },
      { type: "p", text: "Een klant vult een formulier in met wat hij wil. Op basis daarvan stelt het systeem automatisch een concept-offerte op in jouw stijl, klaar voor jouw laatste check. Jij hoeft niet meer vanaf nul te beginnen, je hoeft alleen nog te controleren en te versturen." },
      { type: "h2", text: "Mail-workflow" },
      { type: "p", text: "Binnenkomende mails worden gesorteerd en de routinevragen krijgen een concept-antwoord dat klaarstaat in jouw toon. Veelgestelde vragen over openingstijden, prijzen of beschikbaarheid kun je grotendeels laten afvangen door een slimme chatbot op je site." },
      { type: "h2", text: "Intake-workflow" },
      { type: "p", text: "Een nieuwe klant doorloopt een aantal vragen, en aan het eind heb jij een nette samenvatting plus de juiste vervolgstap. Geen losse mailtjes meer waar je informatie uit moet vissen, maar een vaste route die zichzelf afhandelt." },
      { type: "ul", items: ["Offerte: formulier in, concept-offerte klaar voor check", "Mail: routinevragen automatisch beantwoord of voorgesorteerd", "Intake: vaste route met nette samenvatting aan het eind", "Reserveren: chatbot die zelf afspraken of tafels inplant"] },
      { type: "p", text: "Dat laatste is geen theorie. Voor een restaurant bouwde ik een chatbot die zelf tafels reserveert. Voor Köningsdag in Reusel maakte ik een ticketsysteem met online betaling, zodat de organisatie niet meer met losse lijstjes en contant geld hoefde te werken." },
      { type: "quote", text: "Automatisering is niet je hele bedrijf vervangen. Het is de tien kleine handelingen per dag wegnemen waar niemand blij van wordt." },
      { type: "h2", text: "Hoe je begint zonder groot project" },
      { type: "p", text: "Kies een ergernis die elke dag terugkomt en bouw daar een kleine workflow op. Werkt het, dan pak je de volgende. Zo groeit het organisch, zonder maandenlang project en zonder dat je hele team op zijn kop staat. Klein beginnen wint het hier echt van groots denken." },
      { type: "p", text: "Ik bouwde mijn eigen bedrijfssysteem ook stap voor stap: eerst de uren, toen de facturen, toen de BTW. Geen masterplan, gewoon elke keer het volgende stuk dat me irriteerde. Dat is precies de aanpak die ik ondernemers in de Kempen aanraad." },
      { type: "infographic", infographic: "workflow" },
      { type: "cta", text: "Wil je weten welke mini-workflow voor jouw bedrijf het meest oplevert? Neem contact op of doe de AI-quickscan op mijn site." },
    ],
  },
];
