import type { BlogPost } from "@/lib/blog";

export const AI_POSTS_2: BlogPost[] = [
  {
    slug: "beste-ai-model-2025-eindejaarsvergelijking",
    image: "/blog/ai-content.jpg",
    title: "GPT-5.2 vs Claude vs Gemini: de eindejaarsvergelijking",
    date: "2025-12-15",
    excerpt: "Drie modellen, drie verhalen. Ik gebruik ze allemaal in mijn werk en vertel je nuchter welk model waar uitblinkt, zonder de hype.",
    readTime: "6 min",
    category: "Taalmodellen",
    content: [
      { type: "intro", text: "Aan het einde van 2025 krijg ik bijna wekelijks de vraag: John, welk AI-model moet ik nou kiezen? GPT-5.2, Claude of Gemini? Ik gebruik ze alle drie elke dag in mijn werk voor het MKB in de Kempen. Hier is mijn eerlijke stand van zaken, zonder marketingpraat." },
      { type: "h2", text: "Eerst dit: de verschillen zijn kleiner dan je denkt" },
      { type: "p", text: "De grootste misvatting is dat er een winnaar is. Die is er niet. De drie grote modellen zitten dicht bij elkaar. Voor 80 procent van wat een ondernemer wil doen, maakt de keuze nauwelijks uit. De verschillen zitten in de details en in hoe het model bij jouw manier van werken past." },
      { type: "p", text: "Wat ik wel merk: elk model heeft een eigen karakter. Het ene schrijft strakker, het andere denkt beter na over een lastig probleem, en het derde is sterk als je het koppelt aan andere tools. Daar zit de echte keuze." },
      { type: "h2", text: "Waar elk model in uitblinkt" },
      { type: "ul", items: ["GPT-5.2: breed inzetbaar en snel. Goed eerste model als je net begint, want het kan een beetje van alles en de drempel is laag.", "Claude: sterk in lange teksten, code en redeneren. Ik gebruik het zelf het meest voor het bouwen van mijn Flask-bedrijfssysteem en voor schrijfwerk dat dicht bij mijn eigen stem moet blijven.", "Gemini: handig als je al in Google werkt. De koppeling met Gmail, Docs en zoeken maakt het praktisch voor wie zijn hele administratie daar heeft staan."] },
      { type: "h2", text: "Hoe ik het zelf aanpak" },
      { type: "p", text: "Ik kies niet een model, ik kies per taak. Schrijf ik een offerte of een blog die als ik moet klinken, dan pak ik Claude. Moet ik snel iets opzoeken of samenvatten, dan is het me om het even. Bouw ik aan een chatbot of een automatisering, dan test ik welk model het netste resultaat geeft voor die specifieke klus." },
      { type: "p", text: "Voor een MKB-ondernemer die net start, is mijn advies simpel: begin met een en leer dat goed kennen. Springen tussen drie tools terwijl je de basis nog niet beheerst, kost je meer dan het oplevert." },
      { type: "quote", text: "Het beste model is niet het slimste op papier. Het is het model dat past bij hoe jij werkt en dat je echt elke dag gebruikt." },
      { type: "h2", text: "Wat ik je meegeef voor 2026" },
      { type: "p", text: "Staar je niet blind op benchmarks en cijfers. Die veranderen elke maand en zeggen weinig over jouw dagelijkse werk. Kijk naar wat een model oplevert in jouw situatie: een nettere mail, een snellere offerte, een uur tijdwinst per week. Dat is de enige meting die telt." },
      { type: "cta", text: "Wil je weten welk AI-model past bij jouw bedrijf in de Kempen? Doe de gratis AI-quickscan op mijn site." },
    ],
  },
  {
    slug: "ai-ervaringen-ondernemer-2025",
    image: "/blog/inzichten.jpg",
    title: "Mijn AI-jaar 2025: wat werkte, wat flopte",
    date: "2025-12-22",
    excerpt: "Een eerlijke terugblik op een jaar bouwen met AI voor het MKB. De projecten die scoorden, de dingen die mislukten, en het idee waar ik bewust nee tegen zei.",
    readTime: "6 min",
    category: "AI voor MKB",
    content: [
      { type: "intro", text: "2025 was voor mij het jaar waarin AI van speeltje naar werkpaard ging. Ik bouwde dingen die echt werken voor ondernemers in de Kempen, maar ik liep ook tegen muren aan. Hier is een eerlijke terugblik, zonder de mooie kant te overdrijven." },
      { type: "h2", text: "Wat werkte" },
      { type: "p", text: "Het meeste plezier en het meeste resultaat haalde ik uit kleine, concrete oplossingen. Niet de grote visie, maar het probleem van vandaag. Een paar dingen die echt landden:" },
      { type: "ul", items: ["Mijn eigen Flask-bedrijfssysteem voor uren, facturen en BTW. Ik bespaar er elke maand uren mee en hou eindelijk overzicht.", "Een restaurant-chatbot die reserveringen aanneemt en simpele vragen beantwoordt, zodat de telefoon minder vaak rinkelt tijdens de drukte.", "Een ticketsysteem voor Köningsdag in Reusel, gebouwd voor een lokaal evenement met een concrete deadline."] },
      { type: "h2", text: "Wat flopte" },
      { type: "p", text: "Niet alles lukte. Mijn grootste les: ik bouwde te vaak iets voordat een klant ja had gezegd. Enthousiasme is mooi, maar een demo zonder opdracht is verloren tijd. Een paar keer stak ik dagen in iets dat niemand uiteindelijk afnam." },
      { type: "p", text: "Ook merkte ik dat AI-output zonder duidelijke kaders vaak generiek wordt. De eerste versies van teksten klonken nergens naar. Pas toen ik strak ging sturen op stem en context, werd het bruikbaar." },
      { type: "h2", text: "Het idee waar ik nee tegen zei" },
      { type: "p", text: "Het eerlijkste moment van mijn jaar: ik was bezig met een trading-bot. Ik liet AI een grondige analyse maken van de aanpak, de risico's en de realistische kans op rendement. De conclusie was nuchter en duidelijk: voor mij geen goed idee. Te veel risico, te weinig zicht op een betrouwbaar resultaat, en het hielp niemand verder." },
      { type: "p", text: "Dus zei ik nee tegen mijn eigen idee. Dat voelde even als verlies, maar het was de beste beslissing van het jaar. AI is niet alleen handig om dingen te bouwen. Het is ook handig om je te behoeden voor dingen die je beter niet bouwt." },
      { type: "quote", text: "De waarde van AI zit niet alleen in wat het je laat maken, maar net zo goed in waar het je van weerhoudt." },
      { type: "h2", text: "Wat ik meeneem naar 2026" },
      { type: "p", text: "Eerst het gesprek, dan bouwen. Klein beginnen, snel testen, eerlijk evalueren. En AI inzetten als gereedschap, niet als doel. De ondernemers die dit jaar het meest van AI profiteerden, waren niet degenen met de coolste tools, maar degenen die een echt probleem oplosten." },
      { type: "cta", text: "Benieuwd wat AI concreet voor jouw bedrijf kan betekenen? Plan een gesprek of doe de quickscan." },
    ],
  },
  {
    slug: "ai-trends-2026",
    image: "/blog/ai-camera.jpg",
    title: "7 AI-voorspellingen voor 2026",
    date: "2025-12-29",
    excerpt: "Geen glazen bol, wel een nuchtere blik op waar AI heen gaat. Agents, kleinere modellen en het jaar waarin rendement belangrijker wordt dan hype.",
    readTime: "6 min",
    category: "Toekomst",
    content: [
      { type: "intro", text: "Iedereen doet voorspellingen rond de jaarwisseling, dus laat ik er ook een paar doen. Niet om indruk te maken, maar omdat ik er als bouwer middenin zit. Dit zijn zeven dingen die ik in 2026 verwacht, met beide voeten op de grond." },
      { type: "h2", text: "1. Agents worden volwassen" },
      { type: "p", text: "2025 was het jaar van praten met AI. 2026 wordt het jaar dat AI dingen doet. Agents die meerdere stappen achter elkaar uitvoeren, tools gebruiken en taken afronden zonder dat je elke stap aanstuurt. Voor het MKB betekent dat: minder klikken, meer afhandelen op de achtergrond." },
      { type: "h2", text: "2. Kleinere modellen winnen terrein" },
      { type: "p", text: "Niet elk probleem heeft het grootste model nodig. Kleinere, snellere en goedkopere modellen worden goed genoeg voor veel dagelijkse taken. Dat maakt AI betaalbaarder en bruikbaarder voor een ondernemer met een normaal budget." },
      { type: "h2", text: "3. Rendement boven hype" },
      { type: "p", text: "De fase van wow is voorbij. In 2026 wordt de vraag niet meer kan het, maar levert het iets op. Bedrijven gaan rekenen. Tools die geen tijd of geld besparen, vallen af. Dat is gezond." },
      { type: "h2", text: "De overige vier in het kort" },
      { type: "ul", items: ["Spraak wordt normaal: praten tegen je systemen wordt net zo gewoon als typen, denk aan voice-orchestrators die taken aansturen.", "Lokaal verslaat algemeen: AI die jouw bedrijf, klanten en context kent, wint van generieke chatbots.", "Minder tools, meer integratie: ondernemers stoppen met losse abonnementen en kiezen oplossingen die in hun bestaande werk passen.", "De mens blijft de baas: de winnaars laten AI het zware werk doen, maar houden zelf de regie over toon, keuzes en kwaliteit."] },
      { type: "h2", text: "Waarom ik hier nuchter over blijf" },
      { type: "p", text: "Voorspellingen zijn goedkoop. Ik geef ze omdat ze me helpen kiezen waar ik mijn tijd in stop, niet omdat ik de toekomst ken. De rode draad voor 2026 is simpel: weg van de hype, naar concrete waarde. De ondernemer die dat snapt, hoeft niet elke nieuwe tool te volgen." },
      { type: "quote", text: "2026 is niet het jaar van de slimste AI. Het is het jaar van de AI die zich eindelijk terugverdient." },
      { type: "cta", text: "Wil je AI inzetten op een manier die zich echt terugverdient? Begin met de gratis quickscan op mijn site." },
    ],
  },
  {
    slug: "ai-agents-uitgelegd",
    image: "/blog/ai-content.jpg",
    title: "AI-agents uitgelegd: van chatbot naar digitale collega",
    date: "2026-01-05",
    excerpt: "Een chatbot beantwoordt vragen. Een agent voert taken uit. Ik leg in gewone taal uit wat agentic AI is en wat je er als ondernemer aan hebt.",
    readTime: "5 min",
    category: "AI voor MKB",
    content: [
      { type: "intro", text: "Agentic AI is een van die termen die overal opduikt en die niemand even normaal uitlegt. Dus dat doe ik nu, in gewone taal, zonder jargon. Want zodra je snapt wat een agent is, snap je waarom dit het belangrijkste woord van 2026 wordt." },
      { type: "h2", text: "Het verschil met een gewone chatbot" },
      { type: "p", text: "Een chatbot is reactief. Je stelt een vraag, hij geeft antwoord. Daarna stopt het. Handig, maar beperkt. Een agent is iets anders: die krijgt een doel en gaat zelf aan de slag om dat doel te bereiken. Hij maakt stappen, gebruikt tools en komt terug met een afgerond resultaat." },
      { type: "p", text: "Vergelijk het zo. Een chatbot is een collega die alleen antwoord geeft als je iets vraagt. Een agent is een collega die je een opdracht geeft en die zelf uitzoekt hoe hij die afmaakt." },
      { type: "h2", text: "Een voorbeeld uit mijn eigen werk" },
      { type: "p", text: "Ik bouwde een restaurant-chatbot die reserveringen aanneemt. De eerste versie was een echte chatbot: hij beantwoordde vragen over openingstijden. Maar het werd pas waardevol toen ik er meer agentgedrag in stopte. Nu kijkt hij naar de beschikbaarheid, stelt een tijd voor, legt de reservering vast en bevestigt. Dat is geen vraag-en-antwoord meer, dat is een taak die wordt afgehandeld." },
      { type: "h2", text: "Wat een agent voor jou kan doen" },
      { type: "ul", items: ["Een reservering of afspraak van begin tot eind regelen, niet alleen de vraag beantwoorden", "Een binnenkomende mail lezen, samenvatten en een concept-antwoord klaarzetten", "Gegevens uit verschillende systemen ophalen en bundelen tot een overzicht", "Een terugkerende taak op de achtergrond uitvoeren zonder dat jij erbij hoeft te zijn"] },
      { type: "h2", text: "Waar je realistisch in moet blijven" },
      { type: "p", text: "Een agent is geen tovenaar. Hij maakt fouten, hij heeft duidelijke kaders nodig en je moet hem leren wat goed is in jouw situatie. Voor belangrijke beslissingen wil je een mens die controleert. Het mooie is dat je klein kunt beginnen: een agent voor een afgebakende taak, en uitbreiden als het werkt." },
      { type: "quote", text: "Een chatbot bespaart je een zoekopdracht. Een agent bespaart je een taak. Dat verschil is groter dan het klinkt." },
      { type: "h2", text: "Hoe je begint" },
      { type: "p", text: "Kies een taak die vaak terugkomt en die nu tijd kost. Niet je hele bedrijf, gewoon een ding. Dat is de plek waar een agent zich het snelst terugverdient en waar je het meeste leert." },
      { type: "cta", text: "Wil je weten welke taak in jouw bedrijf zich leent voor een AI-agent? Plan een gesprek of doe de quickscan." },
    ],
  },
  {
    slug: "meest-gebruikte-ai-apps-nederland",
    image: "/blog/inzichten.jpg",
    title: "De 10 meest gebruikte AI-apps in Nederland",
    date: "2026-01-12",
    excerpt: "Welke AI-apps gebruiken Nederlanders echt, en waarvoor zijn ze goed? Een nuchtere lijst met per app het concrete nut voor een ondernemer.",
    readTime: "6 min",
    category: "AI-tools",
    content: [
      { type: "intro", text: "Er zijn duizenden AI-apps, maar het overgrote deel gebruikt niemand. In de praktijk draait het om een handvol tools die je echt elke week opent. Hier is mijn overzicht van de tien die in Nederland het meest gebruikt worden, met per stuk waar je ze voor inzet." },
      { type: "h2", text: "De grote algemene assistenten" },
      { type: "ul", items: ["ChatGPT: de bekendste. Breed inzetbaar voor schrijven, samenvatten, brainstormen en uitleg. Het startpunt voor de meeste mensen.", "Claude: sterk in lange teksten, code en redeneren. Mijn keuze voor schrijfwerk dat dicht bij mijn eigen toon moet blijven.", "Gemini: ingebouwd in Google. Praktisch als je administratie in Gmail en Docs staat.", "Microsoft Copilot: AI in Word, Excel en Outlook. Handig als je in Microsoft 365 werkt."] },
      { type: "h2", text: "De maker-tools" },
      { type: "ul", items: ["Midjourney: voor het genereren van beelden, sfeerimpressies en concepten.", "ElevenLabs: voor stemmen en voice-overs, ook in het Nederlands. Bruikbaar voor video en voice-toepassingen.", "Perplexity: een AI-zoekmachine die antwoorden geeft met bronnen, in plaats van tien blauwe links."] },
      { type: "h2", text: "De werk-tools" },
      { type: "ul", items: ["Notion AI: notities, documenten en kennis doorzoekbaar en samen te vatten.", "Otter en vergelijkbare tools: gesprekken en vergaderingen automatisch uitwerken tot een verslag.", "Canva met AI: snel visuals, posts en simpele ontwerpen maken zonder ontwerpkennis."] },
      { type: "h2", text: "Wat dit lijstje je vertelt" },
      { type: "p", text: "Twee dingen vallen op. Een: de meeste mensen gebruiken een algemene assistent plus een of twee tools voor een specifieke klus. Twee: de winnaars zijn de apps die in je bestaande werk passen. Een losse tool die je apart moet openen, gebruik je na een week niet meer." },
      { type: "p", text: "Voor een MKB-ondernemer is dat goed nieuws. Je hoeft niet alles te kennen. Kies een algemene assistent en een tool voor het ding dat jij vaak doet. Dat is genoeg om serieus tijd te winnen." },
      { type: "quote", text: "De beste AI-app is niet de meest geavanceerde. Het is degene die je zonder erbij na te denken elke dag opent." },
      { type: "h2", text: "Mijn advies" },
      { type: "p", text: "Begin met een. Leer dat goed kennen. Voeg pas een tweede toe als je merkt dat de eerste iets niet goed kan. Zo voorkom je dat je tien abonnementen hebt en er nul echt gebruikt." },
      { type: "cta", text: "Wil je hulp bij het kiezen van de juiste AI-tools voor jouw bedrijf? Doe de gratis quickscan op mijn site." },
    ],
  },
  {
    slug: "beste-ai-tools-2026",
    image: "/blog/ai-camera.jpg",
    title: "Welke AI-tools zijn in 2026 nog relevant (en welke niet)?",
    date: "2026-01-19",
    excerpt: "Na jaren hype is het tijd om op te ruimen. Welke AI-tools verdienen een vaste plek in je werk, en welke kun je rustig laten vallen?",
    readTime: "5 min",
    category: "AI-tools",
    content: [
      { type: "intro", text: "De afgelopen jaren werd elke week een nieuwe AI-tool gelanceerd als de oplossing voor alles. De meeste daarvan bestaan niet meer of doen er niet meer toe. 2026 is het jaar van opruimen. Welke tools verdienen je tijd, en welke kun je vergeten?" },
      { type: "h2", text: "Wat nog relevant is" },
      { type: "p", text: "De tools die blijven, hebben een ding gemeen: ze lossen een echt probleem op dat vaak terugkomt. Geen trucje, maar nut. Dit is wat ik zelf in gebruik hou:" },
      { type: "ul", items: ["Een goede algemene assistent voor schrijven, samenvatten en denken. Dit is de werkpaard die je het meest opent.", "Een transcriptietool die gesprekken en vergaderingen automatisch uitwerkt. Bespaart elke week tijd.", "Tools die in je bestaande systemen zitten, zoals AI in je mail of je documenten. Geen extra app, geen extra drempel.", "Maatwerk dat op jouw bedrijf is gebouwd: een chatbot, een automatisering of een systeem dat jouw context kent."] },
      { type: "h2", text: "Wat je rustig kunt laten vallen" },
      { type: "ul", items: ["Losse tools die maar een klein trucje doen en die je apart moet openen.", "Apps die je drie keer hebt geprobeerd en daarna nooit meer.", "Abonnementen die je vergeten was en die elke maand afschrijven zonder dat je ze gebruikt.", "Tools die indrukwekkend zijn in een demo maar in jouw dagelijks werk niets toevoegen."] },
      { type: "h2", text: "De test die ik zelf gebruik" },
      { type: "p", text: "Ik stel mezelf bij elke tool een vraag: heb ik dit deze maand echt gebruikt, en bespaarde het me tijd of geld? Als het antwoord twee keer ja is, blijft hij. Anders gaat hij eruit. Simpel, maar het werkt. Het scheelt je geld en het maakt je hoofd leeg." },
      { type: "quote", text: "Een tool die je niet gebruikt, is geen investering. Het is een abonnement dat je vergeten bent op te zeggen." },
      { type: "h2", text: "Minder is meer" },
      { type: "p", text: "De valkuil van AI is dat je denkt dat je alles nodig hebt. Het tegendeel is waar. Een paar goede tools die je echt beheerst, leveren meer op dan tien die je half gebruikt. In 2026 win je met focus, niet met een verzameling." },
      { type: "p", text: "Mijn advies aan ondernemers in de Kempen: maak een keer per kwartaal je AI-tools schoon zoals je je mailbox schoonmaakt. Hou wat werkt, gooi de rest weg." },
      { type: "cta", text: "Wil je weten welke AI-tools voor jouw bedrijf echt de moeite waard zijn? Plan een gesprek of doe de quickscan." },
    ],
  },
  {
    slug: "ai-en-eigen-schrijfstijl",
    image: "/blog/ai-content.jpg",
    title: "Hoe werk je samen met AI zonder je eigen stem te verliezen?",
    date: "2026-01-26",
    excerpt: "AI schrijft vlot, maar vaak generiek. Zo zet je AI in als hulp en blijf je toch herkenbaar jezelf in elke tekst.",
    readTime: "6 min",
    category: "AI voor MKB",
    content: [
      { type: "intro", text: "De grootste klacht die ik hoor over AI-teksten: het klinkt nergens naar. Glad, correct en compleet zielloos. Dat is terecht. Maar het ligt niet aan de AI, het ligt aan hoe je hem gebruikt. Je kunt prima met AI werken zonder je eigen stem te verliezen. Dit is hoe ik dat doe." },
      { type: "h2", text: "Waarom AI-teksten generiek klinken" },
      { type: "p", text: "Een taalmodel kiest standaard de meest gemiddelde formulering. Het pakt wat statistisch het meest waarschijnlijk is. Het resultaat is gladde, brave taal die op iedereen lijkt en op niemand. Jouw stem zit juist in de afwijking: hoe jij dingen zegt, welke woorden je vermijdt, hoe direct je bent." },
      { type: "p", text: "Als je dat niet meegeeft, krijg je het gemiddelde terug. En het gemiddelde verkoopt niet, want het valt niet op." },
      { type: "h2", text: "Hoe je je stem bewaart" },
      { type: "ul", items: ["Geef voorbeelden: plak een paar teksten die echt van jou zijn en vraag de AI om die toon aan te houden.", "Benoem je regels: ik laat bijvoorbeeld nooit een gedachtestreepje toe en hou zinnen kort. Zeg dat expliciet.", "Schrijf zelf de eerste zin: zet de toon, laat AI daarna verder helpen in plaats van vanaf nul beginnen.", "Gebruik AI als sparringpartner, niet als ghostwriter: laat het structureren en aanscherpen, jij houdt de pen vast."] },
      { type: "h2", text: "Mijn eigen werkwijze" },
      { type: "p", text: "Ik gebruik AI bijna nooit om iets compleet te laten schrijven. Ik gebruik het om sneller te denken. Ik gooi mijn ruwe gedachten erin, laat het ordenen, en herschrijf daarna in mijn eigen woorden. Het laatste woord is altijd van mij. De tekst die je nu leest is zo ontstaan: AI hielp structureren, ik bepaalde de toon." },
      { type: "h2", text: "De valkuil van te veel polijsten" },
      { type: "p", text: "Hoe vaker je een tekst door AI haalt om hem mooier te maken, hoe meer hij naar het gemiddelde toe kruipt. Op een gegeven moment polijst je je eigen stem eruit. Soms is een wat ruwere, persoonlijke zin sterker dan een perfect geslepen volzin." },
      { type: "quote", text: "AI maakt je sneller, niet anders. Op het moment dat je tekst klinkt als iedereen, ben je de verkeerde kant op aan het slijpen." },
      { type: "h2", text: "Begin met je eigen woorden" },
      { type: "p", text: "Het beste advies dat ik je kan geven: ken je eigen stem voordat je AI inschakelt. Schrijf eens een paar dingen helemaal zelf. Daarna kan AI je versnellen zonder je te vervangen. Andersom werkt niet." },
      { type: "cta", text: "Wil je AI inzetten voor je communicatie zonder dat het generiek wordt? Plan een gesprek, ik denk graag mee." },
    ],
  },
  {
    slug: "ai-specialist-kempen-brabant",
    image: "/blog/inzichten.jpg",
    title: "AI voor de Kempen: zo zetten lokale MKB-bedrijven het in",
    date: "2026-02-02",
    excerpt: "AI is geen ver-van-mijn-bed-show voor grote bedrijven. Juist het MKB in de Kempen kan er nu al concreet van profiteren. En ik kom gewoon langs.",
    readTime: "5 min",
    category: "AI voor MKB",
    content: [
      { type: "intro", text: "Als ik in de Kempen vertel dat ik AI-oplossingen bouw voor het MKB, krijg ik vaak dezelfde reactie: dat is toch iets voor grote techbedrijven in de Randstad? Nee dus. Juist hier, bij de lokale ondernemer, valt nu de meeste winst te halen. En ik woon om de hoek." },
      { type: "h2", text: "Waarom lokaal MKB een voorsprong heeft" },
      { type: "p", text: "Grote bedrijven hebben logge systemen en lange beslislijnen. Een ondernemer in Bladel, Reusel of Veldhoven kan morgen iets uitproberen en overmorgen beslissen of het werkt. Die snelheid is goud waard met AI, want klein beginnen en snel testen is precies de juiste aanpak." },
      { type: "p", text: "Daarbij draait lokaal ondernemen om persoonlijk contact. AI neemt dat niet over, het versterkt het. Het neemt het saaie werk uit handen zodat jij meer tijd hebt voor je klanten." },
      { type: "h2", text: "Concrete voorbeelden uit de regio" },
      { type: "ul", items: ["Een restaurant met een chatbot die reserveringen aanneemt, zodat de telefoon minder rinkelt tijdens de service.", "Een lokaal evenement zoals Köningsdag in Reusel met een eigen ticketsysteem dat de drukte aankan.", "Een ondernemer met een eigen bedrijfssysteem voor uren, facturen en BTW, zodat de administratie geen avonden meer kost.", "Een bedrijf dat klantvragen automatisch laat sorteren en voorbereiden, zodat antwoorden sneller de deur uit gaan."] },
      { type: "h2", text: "Wat het oplevert" },
      { type: "p", text: "Het gaat niet om indrukwekkende techniek. Het gaat om tijd. Een avond minder administratie. Een medewerker die niet meer de hele dag dezelfde vraag beantwoordt. Een reservering die binnenkomt terwijl je dicht bent. Kleine dingen die bij elkaar een groot verschil maken voor een MKB-bedrijf." },
      { type: "quote", text: "AI voor de Kempen gaat niet over de toekomst. Het gaat over een avond eerder naar huis, deze maand al." },
      { type: "h2", text: "Ik kom gewoon langs" },
      { type: "p", text: "Ik geloof niet in oplossingen op afstand bedenken. Ik kom langs, kijk hoe je werkt en luister waar je tijd verliest. Daarna stel ik voor wat haalbaar is, in gewone taal, met een eerlijke prijs. Geen dure trajecten, geen jargon, gewoon iets dat werkt voor jouw bedrijf." },
      { type: "p", text: "Dat is het voordeel van lokaal: je hebt geen contactpersoon in een callcenter, je hebt iemand die om de hoek woont en die je gewoon kunt bellen." },
      { type: "cta", text: "Ondernemer in de Kempen en benieuwd wat AI voor jou kan doen? Doe de quickscan of stuur een bericht, dan kom ik langs." },
    ],
  },
  {
    slug: "claude-sonnet-5-uit",
    image: "/blog/ai-camera.jpg",
    title: "Claude Sonnet 5 is uit: sneller en slimmer, wat merk jij?",
    date: "2026-02-09",
    excerpt: "Er is een nieuwe Sonnet. Sneller, slimmer, scherper. Maar wat betekent dat concreet voor jou als ondernemer? Ik leg het nuchter uit.",
    readTime: "5 min",
    category: "AI-nieuws",
    content: [
      { type: "intro", text: "Claude Sonnet 5 is uit en de techwereld staat weer even op zijn kop. Sneller, slimmer, beter in van alles. Maar ik snap dat je als ondernemer vooral denkt: leuk, maar wat merk ik daarvan? Laat ik dat nuchter uitleggen, zonder de cijferspelletjes." },
      { type: "h2", text: "Wat er nieuw is" },
      { type: "p", text: "Sonnet is het middenmodel van Claude: een balans tussen snelheid en slimheid. De nieuwe versie is merkbaar sneller en gaat beter om met langere en ingewikkeldere taken. Voor wie veel met AI werkt, voelt dat als een collega die net wat scherper is geworden en minder vaak hoeft te worden bijgestuurd." },
      { type: "p", text: "Ik gebruik Sonnet zelf veel voor het bouwen van oplossingen voor klanten. Het verschil dat ik merk is niet spectaculair, maar wel prettig: minder herhalen, nettere eerste versies, sneller resultaat." },
      { type: "h2", text: "Wat het concreet betekent voor jou" },
      { type: "ul", items: ["Sneller antwoord: minder wachten, vooral bij grotere taken zoals lange teksten of meerdere stappen achter elkaar.", "Betere eerste versie: minder corrigeren betekent dat je sneller iets bruikbaars in handen hebt.", "Stabieler bij complexe klussen: het model verliest minder snel de draad in een lange opdracht.", "Gunstiger prijs-prestatie: je krijgt meer waarde voor hetzelfde, wat AI betaalbaarder maakt voor het MKB."] },
      { type: "h2", text: "Moet je nu iets doen?" },
      { type: "p", text: "Nee, niet per se. Als je al met Claude werkt, profiteer je vaak automatisch van de nieuwe versie. Je hoeft niets te installeren of om te bouwen. Het mooie van dit soort updates is dat ze meestal stilletjes je dagelijkse werk verbeteren." },
      { type: "p", text: "Wat ik je wel aanraad: merk je dat je AI vaak moet bijsturen of corrigeren, probeer dezelfde taak dan opnieuw met het nieuwe model. Grote kans dat je minder werk hebt." },
      { type: "quote", text: "De beste AI-updates zijn niet de updates waar je een persbericht over leest. Het zijn de updates die je werk stiller en sneller maken zonder dat je er iets voor hoeft te doen." },
      { type: "h2", text: "Mijn nuchtere conclusie" },
      { type: "p", text: "Een nieuwe Sonnet is geen reden om je hele aanpak om te gooien. Het is een reden om blij te zijn dat het gereedschap waarmee je al werkt, beter is geworden. De echte winst zit niet in welk model je gebruikt, maar in wat je ermee oplost." },
      { type: "cta", text: "Wil je AI inzetten in je bedrijf en altijd met de beste tools werken zonder zelf bij te hoeven houden wat er verandert? Plan een gesprek." },
    ],
  },
  {
    slug: "multi-llm-werken",
    image: "/blog/ai-content.jpg",
    title: "Multi-model werken: waarom slimme teams meerdere AI's gebruiken",
    date: "2026-02-16",
    excerpt: "Niet een AI voor alles, maar de juiste AI per taak. Zo werken slimme teams met ChatGPT, Claude en Gemini naast elkaar, zonder chaos.",
    readTime: "6 min",
    category: "AI-tools",
    content: [
      { type: "intro", text: "Veel ondernemers zoeken naar het ene beste AI-model. Maar de slimste teams die ik tegenkom, doen iets anders: ze gebruiken er meerdere naast elkaar. Niet uit luxe, maar omdat elk model ergens beter in is. Multi-model werken klinkt ingewikkeld, maar dat hoeft het niet te zijn." },
      { type: "h2", text: "Waarom een model niet genoeg is" },
      { type: "p", text: "Je gebruikt thuis ook niet een gereedschap voor alles. Voor een schroef pak je een schroevendraaier, voor een spijker een hamer. Bij AI is het net zo. Het ene model schrijft strakker, het andere redeneert beter, het derde is sterk gekoppeld aan je bestaande systemen. Wie alles in een model propt, laat kwaliteit liggen." },
      { type: "h2", text: "Welk model voor welke taak" },
      { type: "ul", items: ["ChatGPT: snel, breed inzetbaar, goed voor brainstormen en eerste opzetten.", "Claude: sterk in lange teksten, code en redeneren. Mijn keuze voor schrijfwerk en bouwen.", "Gemini: handig als je in Google werkt en informatie uit je eigen mail of documenten wil halen.", "Een gespecialiseerde tool: voor beeld, stem of transcriptie pak je iets dat daar specifiek voor gemaakt is."] },
      { type: "h2", text: "Hoe ik het zelf doe" },
      { type: "p", text: "Ik denk niet in welk abonnement heb ik, ik denk in welke taak heb ik. Een offerte schrijven die als ik moet klinken, gaat anders dan snel iets opzoeken of een stuk code bouwen. Door per klus het juiste model te kiezen, krijg ik betere resultaten en minder gedoe met corrigeren." },
      { type: "p", text: "Het mooie is dat je hiermee ook leert. Door dezelfde taak af en toe in twee modellen te proberen, ontdek je vanzelf welk model waar uitblinkt. Die kennis is meer waard dan welke vergelijking op internet ook." },
      { type: "h2", text: "De valkuil: chaos" },
      { type: "p", text: "Multi-model werken kan ontaarden in chaos: tien abonnementen, geen overzicht en geen idee meer wat je waarvoor gebruikt. Voorkom dat. Begin met twee modellen die elkaar aanvullen, en breid pas uit als je een duidelijke reden hebt. Meer modellen is geen doel, beter resultaat wel." },
      { type: "quote", text: "De slimste teams zoeken niet naar de beste AI. Ze weten welke AI ze waarvoor pakken, net zoals je weet welk gereedschap je uit de kist haalt." },
      { type: "h2", text: "Voor wie is dit?" },
      { type: "p", text: "Als je net begint, hou het bij een model. Multi-model werken is voor wie AI al dagelijks gebruikt en merkt dat een tool niet alles even goed doet. Voor teams die serieus met AI werken, is het bijna onvermijdelijk: je wint kwaliteit en tijd door bewust te kiezen." },
      { type: "cta", text: "Wil je je team slim laten werken met meerdere AI-tools zonder chaos? Plan een gesprek of doe de quickscan op mijn site." },
    ],
  },
];
