import type { BlogPost } from "@/lib/blog";

// Serie uit de echte vragen van MKB-ondernemers (juni-juli 2026).
// Zoekintentie-gedreven: elke post beantwoordt een vraag die ondernemers
// letterlijk stellen over AI in hun bedrijf. Toon: nuchter, op ooghoogte,
// geen hype, geen namen, geen em-dashes.
export const AI_POSTS_4: BlogPost[] = [
  {
    slug: "ai-implementeren-in-je-bedrijf-waar-begin-je",
    title: "AI implementeren in je bedrijf: waar begin je?",
    date: "2026-06-02",
    excerpt:
      "AI implementeren in je bedrijf, waar begin je dan echt? Niet bij een waterval van veertig tools, maar bij een taak deze week. Zo pak je dat aan.",
    readTime: "5 min",
    category: "AI & Automatisering",
    image: "/blog/ai-waar-begin-je.svg",
    content: [
      { type: "intro", text: "Een vraag die ik vaak hoor van ondernemers: AI implementeren in je bedrijf, waar begin je dan eigenlijk? Overal lees je dat je iets met AI moet, maar niemand legt uit wat dat concreet betekent voor een gewone dinsdag op kantoor. Mijn antwoord blijft hetzelfde: begin klein, begin met een taak, en begin deze week." },
      { type: "h2", text: "De vraag die steeds terugkomt" },
      { type: "p", text: "Veel ondernemers zeggen tegen mij zoiets als: het is allemaal leuk en aardig, maar hoe doen we dit nu werkelijk? We zijn hier om te leren hoe we het zelf kunnen doen. Dat is precies de juiste instelling. Geen verhaal over de toekomst van AI, maar een concrete volgende stap voor morgenvroeg." },
      { type: "p", text: "Het probleem is dat de meeste uitleg over AI blijft hangen in wat het allemaal kan. Tekst schrijven, data doorzoeken, agenda's beheren, klantvragen beantwoorden. Een lange lijst met mogelijkheden, maar geen plek om te beginnen. Dat werkt averechts: hoe groter de lijst, hoe langer je wacht met starten." },
      { type: "h2", text: "Kies de klus waar je het minst zin in hebt" },
      { type: "p", text: "De snelste manier om een startpunt te vinden: denk aan de taak die je deze week het minst leuk vond om te doen. Niet de belangrijkste taak, niet de moeilijkste, maar de taak waar je tegenop zag. Dat gevoel is een prima meetlat. Werk waar je energie van wegloopt is meestal repetitief, heeft duidelijke regels en komt steeds in dezelfde vorm terug. Precies het soort werk waar AI goed in is." },
      { type: "ul", items: ["Offertes: een vaste opzet die je telkens opnieuw intypt, met net andere klantgegevens", "Mail: dezelfde vragen, dezelfde toon, iedere keer opnieuw geformuleerd", "Planning: afspraken inplannen, herinneringen versturen, agenda's op elkaar afstemmen"] },
      { type: "p", text: "Geen toevallige voorbeelden. Het zijn de drie taken die het vaakst terugkomen als ik met ondernemers hun week doorneem: klussen die weinig denkwerk vragen, maar wel veel tijd kosten." },
      { type: "h2", text: "Bouw pas op als het werkt" },
      { type: "p", text: "Een vuistregel die ik zelf aanhoud: kijk naar waar je het minst zin in hebt en waar je tijd kunt besparen, en bouw het pas verder op zodra het voor jou goed werkt. Niet andersom. Begin met de kleinste versie die het probleem oplost, gebruik die twee weken in je eigen praktijk, en kijk dan pas of uitbreiden de moeite waard is." },
      { type: "p", text: "Veertig tools tegelijk aanschaffen omdat een lijstje op internet zegt dat ze allemaal onmisbaar zijn, is de snelste weg naar nergens goed in worden. Je hebt dan tien inlogschermen en nul gewoontes. Een taak, echt goed opgelost, levert meer op dan tien halfslachtige experimenten naast elkaar." },
      { type: "h2", text: "Geen 'AI doet alles', wel een duidelijke strategie" },
      { type: "p", text: "Wat de meeste ondernemers missen is niet het verhaal dat AI alles overneemt. Dat verhaal klopt sowieso niet en helpt niemand verder. Wat wel ontbreekt is een antwoord op de vraag waar het voor jouw bedrijf interessant is, en welke aanpak daarbij past, iets wat [mijn werkwijze](/werkwijze) stap voor stap laat zien. Dat is voor elk bedrijf anders. Een aannemer heeft een ander startpunt dan een kapper, en een kapper weer een ander startpunt dan een administratiekantoor." },
      { type: "p", text: "Dat vertalen, van AI kan van alles naar dit ene stukje werkt voor jouw bedrijf, is het werk waar ik mee bezig ben, en precies wat je terugvindt in het verhaal van [iemand die AI bij je bedrijf implementeert](/blog/iemand-die-ai-implementeert-bij-je-bedrijf-brabant). Ik kom langs, kijk mee naar hoe een proces nu loopt, en bouw er iets op dat past bij hoe jij werkt, niet bij een generiek voorbeeld uit een handleiding. En omdat ik het ook beheer vanuit Bladel, in heel Brabant, hoef jij zelf niet uit te zoeken wat je moet doen zodra er iets vastloopt." },
      { type: "cta", text: "Benieuwd welke klus in jouw bedrijf zich als eerste leent voor AI? Doe de gratis AI-quickscan op future-content.nl of plan een vrijblijvend gesprek, dan kijken we samen waar je het beste kunt beginnen." },
    ],
  },
  {
    slug: "ben-ik-geen-it-er-is-ai-iets-voor-mij",
    title: "Ben ik geen IT'er, is AI dan iets voor mij?",
    date: "2026-06-05",
    excerpt:
      "Ben ik geen IT'er, is AI dan iets voor mij? Een vraag die veel zzp'ers en MKB'ers zich stellen. Het antwoord: kun je een appje typen, dan kun je ook AI aansturen.",
    readTime: "4 min",
    category: "AI & Automatisering",
    image: "/blog/ai-geen-it-er.svg",
    content: [
      { type: "intro", text: "Ben ik geen IT'er, is AI dan iets voor mij? Een vraag die ik regelmatig krijg, vaak van zzp'ers en MKB'ers die zich afvragen of AI voor niet-IT'ers eigenlijk wel te doen is. Het korte antwoord: ja. Je hoeft niet te kunnen programmeren om AI te gebruiken. Kun je een appje typen aan een collega, dan kun je ook een AI-tool aansturen. De techniek is niet de drempel. De vertaling naar jouw eigen werk, daar loopt het bij de meeste ondernemers op vast, en precies daar help ik bij, met [AI-oplossingen op maat](/ai) voor je bedrijf." },
      { type: "h2", text: "Zonde van mijn tijd?" },
      { type: "p", text: "Een zorg die ik vaak hoor van zzp'ers: ik ben geen IT'er, en het zou zonde zijn van mijn tijd als het toch niks oplevert. Een volkomen terechte gedachte. Als je alleen werkt, heb je geen ruimte voor een project dat na drie weken uitproberen alsnog niets oplevert. Die voorzichtigheid is geen zwakte, dat is gewoon verstandig ondernemen." },
      { type: "p", text: "Het goede nieuws: AI aansturen vraagt geen technische achtergrond. Geen code, geen syntax, geen ingewikkelde installatie. Je typt in gewone taal wat je wilt, precies zoals je een vraag aan een collega zou stellen." },
      { type: "h2", text: "Wat AI aansturen in de praktijk is" },
      { type: "p", text: "Een agent bouwen klinkt technisch, maar komt in de kern neer op een prompt invoeren: een duidelijke instructie in normale taal, met de context die erbij hoort. Vergelijk het met het inwerken van iemand nieuw. Hoe duidelijker je uitlegt wat je wilt en waarom, hoe beter het resultaat. Die vaardigheid heeft niets met programmeren te maken. Het is dezelfde vaardigheid die je al gebruikt als je een collega instructies geeft of een klant iets uitlegt." },
      { type: "p", text: "Een voorbeeld: typ iets als schrijf een vriendelijke mail om deze afspraak een week te verzetten, en je krijgt bruikbare tekst terug. Meer is het niet. Geen technische term in de buurt." },
      { type: "ul", items: ["Klopt het antwoord niet helemaal? Zeg wat er mis is en vraag om een nieuwe versie", "Te formeel? Vraag om een nuchtere, gewone toon", "Te lang? Vraag om het korter", "Je stuurt bij met gewone taal, zo vaak als nodig is"] },
      { type: "h2", text: "Minder technisch onderlegd is prima" },
      { type: "p", text: "Er zijn ook mensen die minder technisch onderlegd zijn, en dat is gewoon een gegeven, geen tekortkoming. De goede tools zijn juist gebouwd om jou daar te ontmoeten: een chatvenster waarin je in gewone taal typt, geen command line, geen instellingenscherm vol vakjargon. Vraagt een tool wel dat soort kennis van je, dan ligt dat aan de tool, niet aan jou." },
      { type: "h2", text: "Waar het wel om gaat: de vertaling naar jouw werk" },
      { type: "p", text: "De echte drempel zit niet in het bedienen van een AI-tool. Die zit in het vertalen van een algemene tool naar jouw specifieke offertes, jouw klantvragen, jouw manier van plannen. Dat is een ander soort werk dan een knop leren indrukken, en het is precies het werk waar de meeste zzp'ers geen tijd of zin in hebben naast hun eigen vak. Precies daar kom ik in beeld: dat is in de kern [AI laten bouwen voor je bedrijf](/blog/iemand-die-ai-implementeert-bij-je-bedrijf-brabant), ik kijk mee naar hoe jij nu werkt, en bouw daar iets op dat past bij jouw proces, in plaats van een generieke handleiding die overal en nergens op slaat. Ik werk vanuit Bladel, maar kom bij je langs waar je ook zit in Brabant." },
      { type: "p", text: "En zodra het gebouwd is, blijft het niet aan jou hangen. Ik beheer het ook, zodat jij niet ineens zelf IT'er hoeft te worden om het draaiend te houden." },
      { type: "cta", text: "Twijfel je of AI past bij jouw manier van werken? Doe de gratis AI-quickscan op future-content.nl of plan een vrijblijvend gesprek. Geen technisch verhaal, gewoon kijken wat voor jou werkt." },
    ],
  },
  {
    slug: "wat-kost-ai-voor-een-mkb-bedrijf",
    title: "Wat kost AI voor een MKB-bedrijf (en voor zzp'ers)?",
    date: "2026-06-09",
    excerpt:
      "Wat kost AI voor een MKB-bedrijf, of als zzp'er? Eerlijke bedragen: beginnen kan rond de 20 dollar per maand, serieus draaien rond de 200. Dit is hoe je het zelf uitrekent.",
    readTime: "5 min",
    category: "AI & Automatisering",
    image: "/blog/ai-wat-kost.svg",
    content: [
      { type: "intro", text: "Wat kost AI voor een MKB-bedrijf, of voor een zzp'er? Een vraag die bijna iedereen me stelt, en terecht, want niemand wil geld steken in iets vaags. Hier zijn de eerlijke bedragen: beginnen kan al rond de 20 dollar per maand, serieus doorpakken zit eerder rond de 200. Het enige getal dat er echt toe doet, leg ik verderop uit." },
      { type: "h2", text: "Heb je daar als zzp'er wel de ruimte voor?" },
      { type: "p", text: "Een vraag die ik vaak van zzp'ers krijg: heb je daar als zelfstandige wel de middelen voor, want extra geld voor experimenten is er meestal niet. Een volkomen terechte vraag. De meeste zzp'ers hebben geen budget om te experimenteren met iets dat misschien niks oplevert. Het goede nieuws: dat hoeft ook niet. Je kunt met een klein bedrag beginnen, en pas opschalen zodra je zelf ziet dat het iets oplevert." },
      { type: "h2", text: "Het instapbedrag: rond de 20 dollar" },
      { type: "p", text: "Claude kost letterlijk 20 dollar per maand, en dat is een goed voorbeeld van waar de meeste mensen instappen. Voor dat bedrag heb je een AI-assistent die meedenkt over mails, offertes en teksten, en die je helpt bij plannen en uitzoeken. De meeste AI-tools rekenen in dollars, dus reken op een vergelijkbaar bedrag in euro's. Geen jaarcontract, geen implementatietraject, gewoon een abonnement dat je iedere maand weer kunt opzeggen." },
      { type: "h2", text: "Serieus draaien: reken op 200" },
      { type: "p", text: "Zodra je AI breder inzet, bijvoorbeeld met een heel team, met zwaardere taken, of met automatiseringen die op de achtergrond blijven draaien, loop je richting de 200 dollar per maand. Dat klinkt als een sprong, maar zet het naast wat een paar uur extra personeel per maand kost. Neemt AI een paar uur werk per week van je over, dan is dat bedrag snel terugverdiend." },
      { type: "h2", text: "En met meerdere abonnementen tegelijk?" },
      { type: "p", text: "Een vraag die ik regelmatig krijg: wat zijn de maandelijkse kosten als je vier AI-tool-abonnementen hebt en twee agents? Een ruwe indicatie, puur om het beeld concreet te maken." },
      { type: "ul", items: ["Vier tools tussen de 20 en 50 dollar per maand: samen al snel 100 tot 150 dollar", "Een agent die op gebruik draait: meestal een paar tot enkele tientallen dollars per maand, afhankelijk van hoeveel hij verwerkt", "Een agent die op maat gebouwd is: geen abonnement maar een bouwtraject, op aanvraag en per situatie"] },
      { type: "h2", text: "Het nadeel: een stapel losse abonnementjes" },
      { type: "p", text: "Een opmerking die ik vaak terugkrijg: het nadeel zijn al die kleine abonnementjes, veel mensen willen liever plug-and-play. Een eerlijk punt. Vier of vijf losse tools met allemaal een eigen inlog en een eigen factuurdatum is onoverzichtelijk, en daar heeft niemand zin in naast het gewone werk. Een vaste gewoonte helpt al veel: elk kwartaal kort checken welke abonnementen je nog echt gebruikt, en de rest opzeggen. Of je laat iemand anders dat overzicht bewaken, zodat jij alleen het resultaat ziet." },
      { type: "h2", text: "Het enige getal dat echt telt" },
      { type: "p", text: "Alle bedragen hierboven zeggen op zichzelf weinig. Het enige getal dat telt: bespaarde uren maal jouw uurtarief. Bespaar je bijvoorbeeld drie uur per week op offertes of mail, dan reken je dat simpelweg om naar je eigen uurtarief. Komt daar een hoger bedrag uit dan wat de tool kost, dan is de keuze niet moeilijk meer. Komt er niets uit, dan stop je gewoon, zonder schuldgevoel. Twijfel je waar dat bij jou op uitkomt, doe dan de [gratis AI-quickscan](/scan) en je hebt binnen een paar minuten een concreet beeld." },
      { type: "h2", text: "En het bouwwerk zelf?" },
      { type: "p", text: "Voor de tools hierboven geldt een vaste prijs die iedereen betaalt. Voor het bouwen en beheren van automatisering op maat ligt dat anders. Dat hangt af van wat er precies gebouwd moet worden en hoeveel processen het raakt, dus dat bespreken we altijd per bedrijf, op aanvraag. Precies [hoe zo'n traject werkt](/blog/iemand-die-ai-implementeert-bij-je-bedrijf-brabant) leg ik elders stap voor stap uit. Ik werk vanuit Bladel, in heel Brabant, en bouw niet alleen, ik blijf het ook beheren." },
      { type: "cta", text: "Benieuwd wat AI concreet kost voor jouw situatie? Doe de gratis AI-quickscan op future-content.nl of plan een vrijblijvend gesprek, dan rekenen we het samen door." },
    ],
  },
  {
    slug: "is-mijn-bedrijf-te-klein-voor-ai",
    title: "Is mijn bedrijf te klein voor AI?",
    date: "2026-06-12",
    excerpt:
      "Is mijn bedrijf te klein voor AI? Nee, eerder andersom. Als zzp'er of klein bedrijf heb je geen logge IT-afdeling die eerst ja moet zeggen. Dat is precies je voordeel.",
    readTime: "4 min",
    category: "AI & Automatisering",
    image: "/blog/ai-te-klein.svg",
    content: [
      { type: "intro", text: "Is mijn bedrijf te klein voor AI? Die vraag hoor ik geregeld, meestal van zzp'ers en eigenaren van een klein bedrijf. Het beeld dat veel mensen hebben: AI is voor grote bedrijven met een IT-afdeling en tien systemen die op elkaar aangesloten moeten worden. Voor een zaak met twee, drie of vijf man personeel zou het de moeite niet waard zijn. Dat beeld klopt niet, en het staat de zaak eigenlijk op zijn kop. Klein zijn is juist je voordeel." },
      { type: "h2", text: "Waarom klein juist helpt" },
      { type: "p", text: "Bij een groot bedrijf moet een nieuwe manier van werken eerst langs een IT-afdeling, dan een manager, en soms nog een extern bureau erbij. Al die schakels kosten tijd, en onderweg sneuvelt een goed idee vaak voordat het ooit is uitgeprobeerd. Bij een zzp'er of een klein team is die hele keten er niet. Jij beslist zelf, vandaag, zonder overleg met een afdeling die eerst akkoord moet geven. Je hebt één proces dat je wil verbeteren, en je kan er meteen mee beginnen." },
      { type: "p", text: "Een vraag die daarbij vaak naar boven komt: ik heb toch geen 'bedrijf' met een heel IT-ecosysteem of ingewikkelde processen, wat moet AI dan voor mij doen? Dat klopt, en dat is precies waarom AI voor zzp'ers vaak simpeler is dan voor een groot bedrijf. Geen koppelingen tussen tien systemen die allemaal moeten blijven werken, geen goedkeuring van drie managers. Eén helder proces, en dat pak je meteen op, deze week nog." },
      { type: "h2", text: "Je hebt waarschijnlijk al een brondocument" },
      { type: "p", text: "Iets wat vaak over het hoofd wordt gezien: heb je ooit een bedrijfsplan geschreven toen je begon, dan heb je in de basis al een brondocument van wat je wilt. Wie je klant is, wat je aanbiedt, hoe je werkt, welke vragen steeds terugkomen. Precies het soort informatie waarmee AI voor jou aan de slag kan, zonder dat je bij nul begint." },
      { type: "ul", items: ["Een bedrijfsplan of ondernemingsplan: wie je bent en wat je doet", "Standaardmails of offertesjablonen die je nu al gebruikt", "Een vaste werkwijze of checklist die je bij elk project doorloopt", "Vragen die klanten je steeds opnieuw stellen"] },
      { type: "p", text: "Dit soort documenten liggen meestal al ergens op je computer, of gewoon in je hoofd, opgebouwd uit jaren ervaring. Je hoeft ze niet opnieuw te verzinnen. Je verzamelt ze een keer, zodat AI weet in welke toon en met welke informatie het voor jou moet werken." },
      { type: "h2", text: "Klein wordt pas een probleem als je groot begint" },
      { type: "p", text: "De valkuil zit niet in de grootte van je bedrijf, maar in de grootte van de eerste stap, zoals ik ook beschrijf in [AI implementeren in je bedrijf: waar begin je](/blog/ai-implementeren-in-je-bedrijf-waar-begin-je). Een breed AI-traject bedenken voor je hele bedrijf ineens, dat is voor een zzp'er inderdaad te veel, en ook niet nodig. Kies één proces dat elke week terugkomt en tijd kost: een offerte, een intake, een planning, een terugkerende rapportage. Los daar AI op, kijk wat het je concreet oplevert, en beslis pas daarna of je verder gaat." },
      { type: "p", text: "Dit heeft misschien tot nu toe geklonken als een verhaal voor bedrijven met tien man personeel, niet voor een zzp'er. Het is eerder andersom. Omdat jij geen tien afdelingen hoeft af te stemmen en niemand hoeft te overtuigen, kun je dit sneller invoeren dan een groot bedrijf ooit kan. Jouw kleine schaal is geen beperking, het is de reden dat je vandaag al kan beginnen, eventueel samen met [iemand die dit voor je bouwt en beheert](/blog/iemand-die-ai-implementeert-bij-je-bedrijf-brabant)." },
      { type: "cta", text: "Wil je weten waar in jouw eenmansbedrijf of kleine team de eerste stap zit? Doe de gratis AI-Quickscan of plan een vrijblijvend gesprek. Ik bouw en beheer dit soort oplossingen zelf, voor ondernemers in heel Brabant, vanuit Bladel." },
    ],
  },
  {
    slug: "claude-of-chatgpt-welke-ai-kies-je",
    title: "Claude of ChatGPT: welke AI kies je?",
    date: "2026-06-16",
    excerpt:
      "Claude of ChatGPT, welke AI kies je? Je hoeft geen kamp te kiezen. Belangrijker dan de tool is dat je begrijpt waar elke tool sterk in is, en dat je gewoon begint.",
    readTime: "5 min",
    category: "AI & Automatisering",
    image: "/blog/ai-claude-of-chatgpt.svg",
    content: [
      { type: "intro", text: "Claude of ChatGPT, welke AI kies je? En waar past Gemini dan weer bij? Het is een van de vragen die ik het vaakst krijg van ondernemers die willen beginnen met AI. Het korte antwoord: het maakt minder uit dan je denkt, zolang je er maar een kiest en gewoon begint. Het iets langere antwoord staat hieronder." },
      { type: "h2", text: "Stop met een kamp kiezen" },
      { type: "p", text: "Veel mensen behandelen dit alsof het voetbalclubs zijn: je hoort bij team ChatGPT of team Claude, en de rest is minder goed. Dat is onzin. Alle drie de grote tools, ChatGPT, Claude en Gemini, zijn goed genoeg voor het grootste deel van het werk dat een ondernemer of zzp'er dagelijks doet: mails, teksten, samenvattingen, ideeën, vragen beantwoorden. Het verschil zit in de details, niet in een wereld van verschil." },
      { type: "h2", text: "Het verschil tussen Claude, ChatGPT en Gemini" },
      { type: "p", text: "Claude, van het bedrijf Anthropic, valt vooral op bij schrijfwerk waarbij de toon moet kloppen. Het houdt een stijl goed vast door een langer stuk tekst heen, en werkt prettig als je iets in jouw eigen stem laat schrijven of herschrijven. Ook bij het coderen van kleine scripts of automatiseringen werkt Claude doorgaans net wat prettiger. Anthropic's sterkste modellen heten op dit moment Opus 4.8 en Fable 5, met Haiku 4.5 als de snelle, goedkope variant voor simpele klusjes." },
      { type: "p", text: "ChatGPT is de bekendste naam, en niet zonder reden. Het is breed inzetbaar, je vindt overal voorbeelden en uitleg over hoe je het gebruikt, en voor de meeste alledaagse taken doet het gewoon wat je vraagt. Voor wie voor het eerst met AI werkt, is dat een prettige eigenschap: veel mensen om je heen kennen het al en kunnen meedenken." },
      { type: "p", text: "Gemini, van Google, trekt aan het langste eind zodra je al met Gmail, Docs en Drive werkt. Het zit er steeds directer in ingebouwd, waardoor je niet hoeft te kopiëren en plakken tussen een los AI-venster en je document. Ook bij beeld, video en audio is Gemini sterk. Het verschil tussen Claude en Gemini zit hem dus vooral hierin: Claude wint op tekst en toon, Gemini wint op integratie met de tools die je al gebruikt. Werk je al helemaal in Google Workspace, dan is dat een reëel voordeel." },
      { type: "h2", text: "Wat kost het?" },
      { type: "p", text: "Bij Claude begint een instapabonnement bijvoorbeeld rond de 20 dollar per maand. Wil je de zwaarste versie met meer ruimte en snelheid, dan zit je richting de 200 dollar per maand. ChatGPT en Gemini kennen een vergelijkbare opbouw: een gratis of goedkope laag voor de meeste dagelijkse taken, en een duurdere laag voor wie er veel en zwaar gebruik van maakt. Begin bij de instapversie. De meeste ondernemers hebben de zwaarste laag helemaal niet nodig." },
      { type: "h2", text: "Welke tool is interessant als je net begint?" },
      { type: "p", text: "Een vraag die ik veel hoor van mensen die voor het eerst met AI aan de slag gaan: welke tool is nou interessant om mee te starten? Mijn eerlijke advies: dat maakt voor een beginner minder uit dan de reviews je doen geloven. Werk je al veel in Google Workspace, begin dan bij Gemini. Gaat het vooral om teksten schrijven in jouw eigen toon, kijk dan naar Claude. Wil je liever een brede, bekende tool waar je makkelijk hulp over vindt, begin dan bij ChatGPT. Wat je ook kiest: de winst zit niet in de tool, die zit in het wekenlang echt gebruiken en leren hoe je een goede vraag stelt. Wil je een stap verder, waarbij zo'n tool niet alleen antwoord geeft maar het werk ook zelf afrondt, lees dan [wat een AI-agent precies is en oplevert](/blog/wat-is-een-ai-agent-en-wat-levert-het-op). En twijfel je of je dit zelf oppakt of liever [AI laten implementeren](/blog/iemand-die-ai-implementeert-bij-je-bedrijf-brabant) door iemand anders, dat gesprek begint net zo simpel." },
      { type: "cta", text: "Twijfel je nog welke tool of aanpak bij jouw bedrijf past? Doe de gratis AI-Quickscan of plan een vrijblijvend gesprek. Ik help ondernemers in heel Brabant, vanuit Bladel, met het bouwen en beheren van AI en automatisering die past bij hun manier van werken." },
    ],
  },
  {
    slug: "wat-is-een-ai-agent-en-wat-levert-het-op",
    title: "Wat is een AI-agent en wat levert het op?",
    date: "2026-06-19",
    excerpt:
      "Wat is een AI-agent en wat levert het op? Zie het als een digitale collega voor een terugkerend klusje: een opdracht, wat gereedschap en een geheugen.",
    readTime: "5 min",
    category: "AI & Automatisering",
    image: "/blog/ai-wat-is-een-agent.svg",
    content: [
      { type: "intro", text: "Wat is een AI-agent en wat levert het op? Dat is een vraag die ik geregeld krijg, meestal na een gesprek over automatisering. Iedereen kent inmiddels een chatbot die een vraag beantwoordt, maar een agent is net iets anders. Zie het als een digitale collega voor een terugkerend klusje. Niet meer, niet minder." },
      { type: "h2", text: "Een opdracht, wat gereedschap en een geheugen" },
      { type: "p", text: "Een gewone AI-chat wacht op jouw volgende vraag. Jij typt, hij antwoordt, en daar stopt het. Een agent werkt anders: hij krijgt een vaste opdracht mee, hij heeft een paar stukjes gereedschap tot zijn beschikking, zoals een sjabloon invullen of iets opzoeken, en hij onthoudt de context van het gesprek tot de klus is afgerond. Geen los antwoord, maar een afgerond stukje werk." },
      { type: "p", text: "Een vraag die daar meteen achteraan komt: en wat levert die agent dan op, een nieuwe lijst met dingen die ik alsnog zelf moet doen? Nee. Het idee is juist dat de agent het werk zelf afmaakt, niet dat hij jou een nieuwe taak teruggeeft." },
      { type: "h2", text: "Een concreet voorbeeld: de 'offerte maken'-agent" },
      { type: "p", text: "Neem een offerte. Normaal gesproken open je een leeg document, zoek je de juiste gegevens bij elkaar, reken je de uren en het tarief uit, en typ je het netjes uit. Dat kost al snel een uur, soms meer. Ik heb daarvoor zelf, als [iemand die dit soort agents voor bedrijven bouwt](/blog/iemand-die-ai-implementeert-bij-je-bedrijf-brabant), een agent gebouwd die offertes maakt: hij stelt een paar korte vragen over de klant, het project en de uren, en zet daarna zelf de offerte netjes klaar in de juiste opmaak. Van een uur naar een paar minuten, en de opmaak klopt elke keer." },
      { type: "h2", text: "Wat kan een agent nog meer oppakken?" },
      { type: "p", text: "Een offerte-agent is één voorbeeld, maar het principe werkt voor elk terugkerend klusje met een duidelijke structuur." },
      { type: "ul", items: ["Afspraken plannen en bevestigen zonder dat jij zelf de agenda induikt", "Samenvattingen maken van lange mails, verslagen of gesprekken", "Offertes en rapporten opstellen op basis van een paar vaste vragen", "Intake-vragenlijsten van nieuwe klanten verwerken tot een overzicht", "Facturen klaarzetten zodra een klus is afgerond"] },
      { type: "p", text: "Het gaat steeds om hetzelfde patroon: werk dat vaak terugkomt, een vaste structuur heeft, en waar jij nu nog elke keer opnieuw over na moet denken." },
      { type: "h2", text: "Wat het je echt oplevert: tijd" },
      { type: "p", text: "Geen ingewikkeld verhaal over de toekomst van werk. Het levert je vooral tijd op. Een uur dat je nu aan een offerte kwijt bent, wordt een paar minuten. Vermenigvuldig dat met hoe vaak je die klus per maand doet, en je ziet vanzelf waar de winst zit. Die tijd kun je besteden aan meer klanten, of gewoon aan eerder stoppen met werken. Beide zijn een prima uitkomst. Wil je zien welk klusje in jouw bedrijf zich het eerst leent voor zo'n agent, doe dan de [gratis AI-quickscan](/scan)." },
      { type: "cta", text: "Nieuwsgierig welk terugkerend klusje in jouw bedrijf zich leent voor een eigen agent? Doe de gratis AI-Quickscan of plan een vrijblijvend gesprek. Ik bouw dit soort agents zelf, en ik beheer ze ook zelf, voor ondernemers in heel Brabant, vanuit Bladel." },
    ],
  },
  {
    slug: "is-mijn-klantdata-veilig-bij-ai",
    title: "Is mijn klantdata veilig bij AI? Het eerlijke antwoord",
    date: "2026-06-23",
    excerpt:
      "Is mijn klantdata veilig bij AI? Een vraag die ik vaak hoor, en een terechte. Het antwoord zit niet in goede bedoelingen, maar in instellingen die de techniek zelf afdwingt.",
    readTime: "5 min",
    category: "AI & Automatisering",
    image: "/blog/ai-klantdata-veilig.svg",
    content: [
      { type: "intro", text: "Is mijn klantdata veilig bij AI? Dat is een vraag die ik vaak hoor, en een terechte. Je stopt informatie over je klanten in een tool die je niet zelf hebt gebouwd, en je wilt weten waar die informatie blijft. Het goede nieuws: met de juiste instellingen en de juiste tools blijft je data van jou. Het minder goede nieuws: dat gaat niet vanzelf. Je moet het zelf regelen, en weten waar je precies op moet letten." },
      { type: "h2", text: "Een terechte zorg, geen reden om te wachten" },
      { type: "p", text: "Veel ondernemers stellen AI uit omdat ze bang zijn voor wat er met hun klantdata gebeurt. Dat is geen overdreven angst, dat is gezond verstand. Jij bent verantwoordelijk voor de gegevens van je klanten, ook als je ze in een AI-tool plakt in plaats van in je eigen systeem. Die verantwoordelijkheid verdwijnt niet omdat de tool slim is." },
      { type: "p", text: "Maar het is geen reden om AI links te laten liggen. Het is een reden om vooraf drie dingen te regelen: waar je data heen gaat, wie erbij kan, en wat er gebeurt als het misgaat. Regel je dat, dan kun je met een gerust hart aan de slag." },
      { type: "h2", text: "Stemopnames zijn een ander soort risico" },
      { type: "p", text: "Er is een categorie waar ik ondernemers extra alert op wil maken: stemopnames. Steeds meer bedrijven laten gesprekken opnemen en automatisch verwerken, voor een transcript of een samenvatting. Dat voelt onschuldig, het is toch alleen tekst die eruit komt? Maar hoe groot zijn de privacyrisico's eigenlijk als je stemopnames gaat verwerken? Groter dan de meeste mensen denken. Een stemopname zelf is een verwerking van biometrische gegevens, en onder de AVG valt dat in een strengere categorie dan een gewoon tekstbestand of e-mailadres." },
      { type: "p", text: "Dat betekent niet dat je nooit meer een gesprek mag opnemen. Het betekent wel dat je bewust kiest waar die opname naartoe gaat, hoelang hij bewaard blijft en wie er toegang toe heeft. Voor gesprekken met klanten, patiënten of medewerkers is dat geen bijzaak. Dat is de kern van hoe je het inricht." },
      { type: "h2", text: "De techniek moet de muur zijn, niet je gedrag" },
      { type: "p", text: "De meest gemaakte fout die ik zie: bedrijven vertrouwen op afspraken in plaats van op techniek. We zeggen tegen het team dat ze voorzichtig moeten zijn met klantgegevens. Dat werkt tot iemand een lange dag heeft en het net iets te snel doet. Voor echt gevoelige klantdata moet de techniek de muur zijn, niet alleen je gedrag of je goede bedoelingen." },
      { type: "ul", items: ["Kies een tool met een verwerkersovereenkomst, niet alleen een gratis consumentenversie", "Zet de instelling uit die jouw gegevens gebruikt om het model verder te trainen", "Regel toegang per rol: niet iedereen in je team hoeft overal bij te kunnen", "Leg vast waar de data wordt opgeslagen en hoelang, in plaats van dat te vermoeden", "Behandel stemopnames met extra zorg: kies voor verwerking die aantoonbaar niet wordt hergebruikt"] },
      { type: "h2", text: "Een aparte laptop is geen security-fix" },
      { type: "p", text: "Ik hoor ook weleens dezelfde oplossing voorbijkomen: een bedrijf koopt een aparte laptop voor het AI-werk, los van de rest van de zaak. Dat voelt als een veilige knip, maar het lost het eigenlijke probleem niet op. Zodra die laptop verbinding maakt met dezelfde clouddienst of hetzelfde account gebruikt, ben je terug bij af. Een apart apparaat verandert niets aan waar je data heen gaat of wie erbij kan. Een aparte laptop kopen is geen security-fix, het is een gevoel van veiligheid zonder de techniek die het ook waarmaakt." },
      { type: "p", text: "Wat wel helpt is duidelijkheid over de tool zelf: welke instelling staat aan, welke overeenkomst ligt eronder, wie heeft toegang. Dat is minder zichtbaar dan een los kastje op een bureau, maar het is precies de plek waar het risico zit." },
      { type: "h2", text: "Hoe je dit praktisch aanpakt" },
      { type: "p", text: "Ga per proces na welke data erin gaat: een naam, een adres, een factuurbedrag, of iets gevoeligers zoals een stemopname of een medisch detail. Kies daarna een tool die past bij dat niveau, niet andersom. En leg vast wat je hebt afgesproken, ook al is het maar een half A4'tje. Dat is het verschil tussen we doen ons best en een opzet die ook standhoudt op het moment dat het erop aankomt, en dat soort uitzoekwerk hoort standaard bij [een AI-traject dat ook na de bouw beheerd wordt](/blog/iemand-die-ai-implementeert-bij-je-bedrijf-brabant)." },
      { type: "cta", text: "Twijfel je of jouw manier van werken met AI je klantdata echt beschermt? Ik bouw en beheer AI-systemen voor bedrijven in heel Brabant, vanuit Bladel, en denk daar graag in mee. Doe de gratis AI-Quickscan op future-content.nl, of stuur een bericht voor een gesprek." },
    ],
  },
  {
    slug: "wat-ai-niet-kan-en-waarom-dat-goed-is",
    title: "Wat kan AI niet? De grenzen van AI voor je bedrijf",
    date: "2026-06-26",
    excerpt:
      "Wat kan AI niet? Een vraag die te weinig gesteld wordt. Wie de grenzen van AI eerlijk benoemt, gebruikt het beter en houdt het echte contact waar het hoort: bij jou.",
    readTime: "5 min",
    category: "AI & Automatisering",
    image: "/blog/ai-wat-ai-niet-kan.svg",
    content: [
      { type: "intro", text: "Iedereen praat over wat AI allemaal kan. Teksten schrijven, agenda's plannen, gesprekken samenvatten, zelfs een hele strategie uittekenen. Minder mensen vragen: wat kan AI niet? Dat is jammer, want juist die grens is waar je als ondernemer het meest aan hebt. Wie eerlijk is over wat AI niet kan, gebruikt het beter en wint bovendien vertrouwen bij iedereen die meekijkt." },
      { type: "h2", text: "AI ziet niet wat jij niet opschrijft" },
      { type: "p", text: "Een AI werkt met wat je erin stopt. Niet meer, niet minder. Het ziet niet waar je in je bedrijf op vastloopt als je dat niet benoemt. Het voelt niet aan waar je blij van wordt, tenzij je dat vertelt. Het weet niets van de klant die al tien jaar terugkomt, of van de collega die net iets anders werkt dan er op papier staat. Dat is geen gebrek aan intelligentie. Het is de aard van het ding: het reageert op wat er voor hem ligt, niet op wat er in jouw hoofd zit." },
      { type: "p", text: "Ook het nieuwste model verandert daar niets aan. Of je nu met Opus 4.8 werkt of met Fable 5: sneller en preciezer, zeker, maar het ziet nog steeds niet wat jij niet opschrijft. Hoe meer context je geeft, hoe beter het werkt. Maar er blijft altijd een deel dat jij zelf moet aanleveren, gewoon omdat jij het enige bent die het weet." },
      { type: "h2", text: "Een strategie die klopte, maar niet paste" },
      { type: "p", text: "Ik heb dit zelf meegemaakt. Ik liet een AI een contentstrategie uitwerken op basis van alles wat ik erover had verteld. Het resultaat was professioneel: logisch opgebouwd, goed geformuleerd, precies volgens het boekje. En toch klopte het niet. Het las als een strategie die voor honderd bedrijven tegelijk kon gelden, niet specifiek voor mij. De AI bouwde een strategie die professioneel klopte, maar niet wie ik was." },
      { type: "p", text: "Dat is een patroon dat ik vaker zie. AI is sterk in structuur en in het volgen van een format. Het is zwak in het aanvoelen van net dat ene detail dat een bedrijf of een mens onderscheidt van de rest. Die aanvoeling moet je zelf toevoegen. Niemand anders doet dat voor je." },
      { type: "h2", text: "Waarom ik afraad om content volledig op de automaat te zetten" },
      { type: "p", text: "Er bestaan tools die volledig automatisch blijven posten, dag in dag uit, zonder dat er nog een mens naar kijkt. Ik snap de aantrekkingskracht, het scheelt tijd. Toch raad ik het af, en niet omdat het technisch niet zou werken. Het werkt prima, tot je jezelf de vraag stelt die er echt toe doet: als straks alle posts door AI gemaakt zijn, wie leest dat dan nog? Op het moment dat iedereen dezelfde tool gebruikt om hetzelfde soort tekst te produceren, verdwijnt precies het ding waarmee jij je onderscheidt." },
      { type: "p", text: "Klanten voelen het verschil tussen een bericht dat gemaakt is en een bericht dat gevoeld is, ook al kunnen ze niet altijd benoemen waarom. Dat verschil is waar vertrouwen vandaan komt, en dat wil je niet wegautomatiseren voor een paar uur tijdwinst." },
      { type: "h2", text: "Automatiseer het gedoe, niet het contact" },
      { type: "p", text: "Het goede nieuws: er is genoeg gedoe rond je bedrijf dat je wel volledig kunt automatiseren, zonder dat het ten koste gaat van wie je bent. Denk aan een eerste concept van een tekst, het plannen van berichten, het samenvatten van een lang gesprek, het klaarzetten van een offerte: precies het soort werk dat aan bod komt bij [wat AI voor je bedrijf kan doen](/ai). Dat is administratief werk, geen vakwerk." },
      { type: "ul", items: ["Wat je gerust automatiseert: planning, eerste concepten, samenvattingen, herinneringen, het sorteren van mail", "Wat bij jou blijft: het echte gesprek met een klant, de beslissing in een lastige situatie, de toon die bij jouw merk past, het vakwerk waar de klant voor betaalt"] },
      { type: "p", text: "Zet die twee naast elkaar en je ziet meteen waar de winst zit. Niet in minder mens, maar in minder gedoe." },
      { type: "h2", text: "Eerlijk over grenzen wint vertrouwen" },
      { type: "p", text: "Ik merk dat ondernemers opgelucht reageren zodra ik vertel wat AI niet kan, in plaats van alleen te verkopen wat het wel kan. Het klinkt geloofwaardiger, en dat is het ook. Een systeem dat feilloos alles overneemt bestaat niet, en wie dat belooft, kun je beter wantrouwen. Een systeem dat het gedoe wegneemt en jou vrij maakt voor het werk waar jij goed in bent, dat bestaat wel: dat is precies wat je krijgt bij [een specialist die het voor je bouwt en blijft beheren](/blog/iemand-die-ai-implementeert-bij-je-bedrijf-brabant). Dat is het verschil waar ik naar op zoek ben, elke keer weer." },
      { type: "cta", text: "Wil je weten wat AI voor jouw bedrijf wel en niet moet overnemen? Ik bouw en beheer die systemen, voor bedrijven in heel Brabant, vanuit Bladel. Doe de gratis AI-Quickscan op future-content.nl, of stuur een bericht voor een gesprek." },
    ],
  },
  {
    slug: "ai-voor-vakmensen-werk-je-met-je-handen",
    title: "AI voor vakmensen: je handen blijven, het papierwerk niet",
    date: "2026-06-30",
    excerpt:
      "AI voor vakmensen klinkt al snel als een tegenstelling: je werkt met je handen, dus wat moet je met een computerprogramma? Terechte vraag. Je vak blijft van jou, maar het papierwerk eromheen mag best wat hulp krijgen.",
    readTime: "4 min",
    category: "AI & Automatisering",
    image: "/blog/ai-vakmensen.svg",
    content: [
      { type: "intro", text: "AI voor vakmensen voelt voor veel installateurs, monteurs en kappers als een tegenstelling. Je werkt met je handen, met vakmanschap dat je jarenlang hebt opgebouwd. Een vraag die ik daarom vaak hoor is kort en duidelijk: ik werk met mijn handen, dus ik haak hier nu echt af. Helemaal terecht, en toch klopt het maar voor de helft. Want je vak blijft van jou. Het is het papierwerk eromheen waar AI je tijd teruggeeft, niet je vak zelf." },
      { type: "h2", text: "Je vak blijft gewoon van jou" },
      { type: "p", text: "Laat dit voorop staan: AI legt geen dakpannen, knipt geen haar en stelt geen motor af. Dat is precies waarom een klant jou belt en geen app. Vakmanschap zit in je handen, je ervaring en je oog voor wat er mis is nog voordat de klant het zelf ziet. Daar verandert AI helemaal niets aan, en dat hoort ook zo. Sterker nog: hoe minder tijd je kwijt bent aan administratie, hoe meer ruimte er overblijft voor het vak zelf." },
      { type: "p", text: "Wat wel verandert, is alles eromheen. De offerte die je 's avonds laat nog uittypt. De mail die blijft liggen tot na sluitingstijd. De planning die je in je hoofd of op een whiteboard bijhoudt. De klant die je nog moet terugbellen, maar waar je tussen twee klussen door niet aan toekomt." },
      { type: "h2", text: "Het echte tijdverlies zit niet in het vak" },
      { type: "p", text: "Een andere reactie die ik vaak terugkrijg zit dichter bij de kern: wij werken ook met onze handen, maar om je klanten efficiënt te kunnen antwoorden kan je toch AI gaan gebruiken? Precies. Het vak zelf hoeft niet sneller. Maar alles ervoor en erna, daar zit tijdwinst zonder dat je kwaliteit inlevert, en wat dat concreet kost lees je in [wat AI kost voor een mkb-bedrijf](/blog/wat-kost-ai-voor-een-mkb-bedrijf)." },
      { type: "ul", items: ["Installateur: een storing komt binnen via WhatsApp, en jij krijgt automatisch een samenvatting met adres, klacht en urgentie, in plaats van dat je tussen het werk door je telefoon moet checken.", "Monteur: een offerte voor een onderhoudsbeurt staat al klaar op basis van het kenteken en de vorige factuur. Jij checkt het bedrag en verstuurt.", "Kapper: klanten boeken zelf een moment in een systeem dat je agenda kent, in plaats van dat jij tussen twee knipbeurten door de telefoon moet opnemen."] },
      { type: "h2", text: "Ook als je vak zelf niet te automatiseren is" },
      { type: "p", text: "Niet elk vak leent zich voor automatisering, en dat is geen probleem. Ik hoor bijvoorbeeld ook: ik repareer klassieke auto's, dat wordt lastig voor AI, wel kan het me helpen met website en LinkedIn bijhouden. Precies dat klopt voor het grootste deel van de vakken die ik tegenkom. Een klassieker restaureren, een dak leggen, een keuken plaatsen: dat blijft precisie en gevoel die niemand kan overnemen. Maar de website die al twee jaar niet is bijgewerkt, of de LinkedIn-pagina die stof verzamelt, daar helpt AI je wel bij. Denk aan een bericht dat klaarstaat na een mooie klus, met de foto's die je toch al maakte." },
      { type: "h2", text: "Waar ik dan wel mee help" },
      { type: "p", text: "Ik bouw geen systeem dat jouw vak overneemt. Als [AI-specialist die langskomt bij je bedrijf](/blog/iemand-die-ai-implementeert-bij-je-bedrijf-brabant) bouw en beheer ik de zaken eromheen: een mailbox die zichzelf sorteert, een planning die zichzelf bijhoudt, offertes en facturen die grotendeels zichzelf schrijven, klanten die op tijd worden teruggebeld zonder dat jij het hoeft te onthouden. Meestal beginnen we klein, bij die ene herhaaltaak die je al jaren ergert, en bouwen we pas verder als dat eerste stukje aantoonbaar tijd oplevert." },
      { type: "p", text: "Dit gaat niet over innoveren omdat het moet. Het gaat over 's avonds op tijd stoppen, in het weekend niet aan facturen denken, en overdag gewoon het vak doen waar je goed in bent. Dat is de winst, niet een dashboard vol grafieken." },
      { type: "cta", text: "Herken je dit uit je eigen bedrijf? Een kort en vrijblijvend gesprek laat zien of het iets oplevert, zonder verplichtingen. Ik werk voor ondernemers in heel Brabant, vanuit Bladel." },
    ],
  },
  {
    slug: "iemand-die-ai-implementeert-bij-je-bedrijf-brabant",
    title: "Op zoek naar iemand die AI kan implementeren bij je bedrijf? Zo werkt dat",
    date: "2026-07-03",
    excerpt:
      "Je hebt genoeg gelezen over wat AI allemaal kan. Je zoekt gewoon iemand die AI kan implementeren bij je bedrijf, iemand die het komt bouwen. Als AI-specialist in Brabant leg ik hier eerlijk uit hoe dat traject eruitziet, van kennismaking tot een systeem dat blijft draaien.",
    readTime: "5 min",
    category: "AI & Automatisering",
    image: "/blog/ai-implementeren-brabant.svg",
    content: [
      { type: "intro", text: "Op een gegeven moment heb je genoeg artikelen gelezen over wat AI allemaal kan. Dan wil je niet nog een lijstje met tools of nog een blog over kansen. Dan zoek je iemand die AI kan implementeren bij je bedrijf, iemand die langskomt en het echt bouwt. Een vraag die ik daarom vaak krijg is kort: wie doet dit voor mijn bedrijf, en hoe gaat dat dan in z'n werk? Hier is het eerlijke antwoord: dezelfde stappen die ook op de pagina [werkwijze](/werkwijze) staan, in de volgorde waarin het bij mij ook echt gaat." },
      { type: "h2", text: "Stap 1: een vrijblijvend gesprek" },
      { type: "p", text: "Het begint met bellen, appen, of me gewoon uitnodigen voor een bak koffie. Geen verkooppraatje, geen halfuur waarin ik probeer je te overtuigen. Gewoon kijken of het klikt en of er überhaupt iets te bouwen valt. Kost je niets, en je zit nergens aan vast." },
      { type: "h2", text: "Stap 2: de workshop op locatie" },
      { type: "p", text: "Klikt het, dan volgt een workshop bij jou op kantoor of in de zaak. Geen praatje met slides: we duiken samen je bedrijf in, op dezelfde manier waarop ik ook beschrijf [waar je met AI het beste kan beginnen](/blog/ai-implementeren-in-je-bedrijf-waar-begin-je). Welk werk komt elke week terug, waar gaat de meeste tijd in zitten, welke mail of planning kost onnodig veel energie. Vaak gebruiken we gewoon wat er al ligt: een mailbox vol offerteaanvragen, een Excel-planning, facturen van de afgelopen maanden. Aan het eind van die dag lever ik geen adviesrapport op papier, maar een werkend proof of concept, gebouwd op jullie eigen data. Je ziet die dag zelf of het werkt, voordat je ergens ja tegen zegt." },
      { type: "h2", text: "Stap 3: een offerte, en ik bouw het" },
      { type: "p", text: "Werkt het, en willen jullie door, dan krijg je een heldere offerte op basis van wat er in de workshop naar boven kwam, met bedragen in dezelfde orde van grootte als in [wat AI kost voor een mkb-bedrijf](/blog/wat-kost-ai-voor-een-mkb-bedrijf). Geen verrassingen achteraf, geen kleine lettertjes. Zeg je ja, dan bouw ik het verder uit tot een systeem dat past bij hoe jullie nu al werken, niet andersom." },
      { type: "h2", text: "Stap 4: ik beheer het ook" },
      { type: "p", text: "Hier stopt het bij veel bureaus: project opgeleverd, factuur verstuurd, tot ziens. Bij mij niet. Ik blijf beheerder van wat ik bouw: updates, onderhoud, aanpassingen als je bedrijf verandert of als er een nieuwe versie van een AI-model uitkomt die iets beters mogelijk maakt. Je staat er niet alleen voor als er iets hapert of als je een uitbreiding wilt. We spreken gewoon af hoe vaak we even bijpraten." },
      { type: "h2", text: "Niet zomaar een bureau of een freelancer erbij" },
      { type: "p", text: "AI laten implementeren bij je MKB-bedrijf kun je op veel manieren aanpakken: een groot bureau inhuren, een freelancer via een platform, of het zelf uitzoeken naast je gewone werk. Allemaal prima opties, maar ze hebben één ding gemeen: iemand op afstand die jouw bedrijf niet kent voordat de eerste factuur binnenkomt. Ik werk andersom. Eerst kennismaken, eerst je bedrijf zien, en pas daarna bouwen. Dat kost aan de voorkant iets meer tijd, en scheelt achteraf een hoop ruis." },
      { type: "h2", text: "Waarom vanuit Bladel, in heel Brabant" },
      { type: "p", text: "Ik werk vanuit Bladel en kom bij je langs in heel Brabant. Niet omdat dat een leuke slogan is, maar omdat AI laten implementeren bij je bedrijf volgens mij begint met iemand die aan tafel zit en meekijkt, niet met een partij die op afstand een systeem aflevert. Als AI-specialist met een lokale basis ken ik de bedrijven in deze regio, kom ik gewoon fysiek langs voor de workshop, en zit er geen vreemde tussenpersoon tussen jou en degene die het bouwt." },
      { type: "h2", text: "Eerlijk over wat ik wel en niet beloof" },
      { type: "p", text: "Ik beloof geen wonderen. Soms is het eerlijke advies dat je beter zelf verder kunt met een goede prompt in ChatGPT, en dan zeg ik dat ook gewoon. Ik neem alleen aan wat ik ook echt kan waarmaken, en verder beheren." },
      { type: "p", text: "Wil je eerst zelf zien waar in jouw bedrijf AI iets kan opleveren, zonder meteen een gesprek in te plannen? Doe de [gratis scan](/scan) op deze site. Je vult je website in en krijgt binnen een paar minuten drie concrete AI-kansen voor je eigen bedrijf." },
      { type: "cta", text: "Klaar om verder te praten? Plan een vrijblijvend gesprek en we kijken samen of er iets te bouwen valt voor jouw bedrijf." },
    ],
  },
];
