import type { BlogPost } from "@/lib/blog";

// Serie 5: de inhaalslag juli en augustus 2026.
// Eén focus: AI en automatisering voor MKB-bedrijven. Geen video, geen makelaars.
// Elke post beantwoordt een vraag die ondernemers letterlijk stellen.
// Toon: nuchter, op ooghoogte, doorgerekend, geen hype, geen em-dashes.
export const AI_POSTS_5: BlogPost[] = [
  {
    slug: "ai-voor-offertes-sneller-offreren",
    title: "AI voor je offertes: van een uur naar tien minuten",
    date: "2026-07-07",
    excerpt:
      "Offertes maken kost de meeste MKB-bedrijven meer tijd dan ze denken. Niet omdat het moeilijk is, maar omdat je telkens hetzelfde opnieuw typt. Zo pak je dat aan met AI.",
    readTime: "5 min",
    category: "AI & Automatisering",
    image: "/blog/ai-offertes.png",
    content: [
      { type: "intro", text: "Vraag een ondernemer hoe lang hij over een offerte doet en je krijgt bijna altijd hetzelfde antwoord: een half uurtje. Ga je het echt bijhouden, dan blijkt het een uur tot anderhalf uur te zijn. Prijzen opzoeken, de vorige offerte erbij pakken, teksten aanpassen, controleren of je niks vergeten bent. En dat vijf tot tien keer per week." },
      { type: "h2", text: "Waarom offertes zo veel tijd kosten" },
      { type: "p", text: "Een offerte is geen creatief werk. Het is opzoekwerk plus overtypen. De structuur ligt vast, de voorwaarden liggen vast, je tarieven liggen vast. Wat verandert is de klant, de omvang en een paar regels tekst over de specifieke situatie. In tijd is dat misschien tien procent van het werk. De andere negentig procent doe je elke keer opnieuw." },
      { type: "p", text: "Daar komt bij dat je het meestal tussendoor doet. Tussen twee klussen in, aan het eind van de dag, of in het weekend. Dat is precies het moment waarop je fouten maakt: een verkeerd tarief, een oude clausule, een naam die van de vorige klant is blijven staan." },
      { type: "h2", text: "Wat AI hier concreet doet" },
      { type: "p", text: "De winst zit niet in AI die de offerte verzint. De winst zit in AI die de bekende delen invult en jou alleen de keuzes laat maken die echt van jou zijn. Je geeft de kern door, bijvoorbeeld wat de klant nodig heeft en hoeveel werk het is, en je krijgt een concept terug dat al in jouw structuur en jouw toon staat." },
      { type: "ul", items: [
        "Je eigen tarieven en staffels staan vast in het systeem, dus die kunnen niet verschuiven",
        "De standaardteksten en voorwaarden komen automatisch mee in de juiste versie",
        "De klantgegevens komen uit je administratie, niet uit een kopie van de vorige offerte",
        "Je krijgt een concept, geen eindproduct: jij leest na en past aan waar het moet",
      ] },
      { type: "p", text: "Dat laatste punt is het belangrijkste. Een offerte die zonder jouw ogen de deur uitgaat is een risico, geen tijdwinst. Het doel is dat je van typen naar controleren gaat, en controleren kost nu eenmaal minder tijd." },
      { type: "h2", text: "Beginnen zonder eerst iets te bouwen" },
      { type: "p", text: "Je hoeft hier geen software voor te laten maken om te weten of het werkt. Pak je laatste vijf offertes en kijk wat er in alle vijf hetzelfde is. Dat is je sjabloon. Wat verschilt zijn je variabelen. Als je die twee lijstjes hebt, kun je met een goed opgezette prompt binnen een middag testen of het klopt." },
      { type: "p", text: "Werkt het, dan is de volgende stap het vastzetten zodat je het niet elke keer opnieuw hoeft uit te leggen. Dat kan een custom instructie zijn, een template in je bestaande pakket, of een klein systeem dat aan je administratie hangt. Welke vorm het wordt hangt af van hoe vaak je het doet en wie het nog meer moet kunnen gebruiken." },
      { type: "h2", text: "Waar het misgaat" },
      { type: "ul", items: [
        "Je laat AI ook de prijs bepalen. Doe dat niet. Prijs is een beslissing, geen berekening.",
        "Je gebruikt een generiek voorbeeld van internet in plaats van je eigen laatste offertes als basis.",
        "Je slaat de controle over omdat het concept er goed uitziet. Er staat altijd iets in dat niet klopt.",
        "Je bouwt meteen iets groots terwijl je nog niet weet of het sjabloon zelf deugt.",
      ] },
      { type: "p", text: "Offertes zijn een goed startpunt omdat de winst direct meetbaar is. Je weet hoeveel je er per week maakt en je voelt binnen twee weken of het scheelt. Dat maakt het een van de weinige AI-toepassingen waarbij je niet hoeft te discussiëren over of het iets oplevert." },
      { type: "cta", text: "Benieuwd of jouw offerteproces zich hiervoor leent? Doe de gratis AI-quickscan of plan een vrijblijvend gesprek, dan kijk ik met je mee naar hoe het nu loopt." },
    ],
  },
  {
    slug: "mailbox-automatiseren-met-ai",
    title: "Je mailbox automatiseren met AI: wat werkt en wat niet",
    date: "2026-07-11",
    excerpt:
      "De mailbox is voor veel ondernemers de grootste tijdvreter. AI kan er flink in snijden, maar niet op de manier die de meeste tools beloven.",
    readTime: "5 min",
    category: "AI & Automatisering",
    image: "/blog/ai-mailbox.png",
    content: [
      { type: "intro", text: "Als ik ondernemers vraag waar hun dag heen gaat, komt de mailbox bijna altijd als eerste. Niet omdat mail zo moeilijk is, maar omdat het de hele dag door binnendruppelt en je telkens uit je werk haalt. De vraag is dus niet of AI je mail kan schrijven, maar of AI die onderbreking kan wegnemen." },
      { type: "h2", text: "Wat de meeste tools beloven en wat er dan gebeurt" },
      { type: "p", text: "De standaardbelofte is: AI beantwoordt je mail. Klinkt goed, werkt zelden. Een antwoord dat automatisch de deur uitgaat is precies het antwoord waar je klant aan merkt dat er geen mens naar gekeken heeft. En bij de ene mail waar het wel echt om iets gaat, is dat meteen een probleem." },
      { type: "p", text: "Wat wel werkt is een stap eerder: zorgen dat je niet meer alle mail hoeft te lezen om te weten wat er belangrijk is. Dat is een sorteervraag, geen schrijfvraag, en daar is AI opvallend goed in." },
      { type: "h2", text: "Drie dingen die wel werken" },
      { type: "ul", items: [
        "Sorteren op wat het is: een offerte-aanvraag, een factuurvraag, een leverancier, ruis. Je opent alleen nog wat aandacht vraagt.",
        "Samenvatten van lange draden. Een mailwisseling van veertien berichten waar je halverwege instapt, teruggebracht tot wat er is afgesproken en wat er open staat.",
        "Concepten klaarzetten voor de vragen die je vaak krijgt, in jouw toon, zodat jij alleen nog leest en verstuurt.",
      ] },
      { type: "p", text: "Die derde is de belangrijkste en meteen de meest onderschatte. Het verschil tussen automatisch versturen en een concept klaarzetten lijkt klein, maar het is het verschil tussen een systeem dat je vertrouwt en een systeem dat je uitzet na de eerste blunder." },
      { type: "h2", text: "Wat je beter met rust laat" },
      { type: "p", text: "Klachten, onderhandelingen en alles waar geld of emotie in zit: daar moet je zelf aan. Niet omdat AI het niet kan formuleren, maar omdat de toon in die berichten de inhoud is. Een klant die boos is wil merken dat een mens het gelezen heeft." },
      { type: "p", text: "Ook oppassen met alles wat aan je agenda of je administratie hangt zonder tussenstap. Een AI die zelfstandig afspraken verzet of facturen doorzet, gaat een keer iets doen wat je niet had gewild. Zet daar altijd een bevestiging tussen, ook al voelt dat als een omweg." },
      { type: "h2", text: "Hoe je het opzet zonder je hele mail om te gooien" },
      { type: "p", text: "Begin met één categorie. Neem de vraag die je het vaakst krijgt en kijk hoe je die nu beantwoordt. Verzamel je laatste tien antwoorden op die vraag, want daarin zit je toon en je standaardinformatie. Op basis daarvan zet je een concept-generator op, en die gebruik je twee weken. Pas als dat rustig loopt, komt de volgende categorie erbij." },
      { type: "quote", text: "De winst zit niet in sneller antwoorden. De winst zit in minder vaak hoeven kijken." },
      { type: "p", text: "Reken het ook echt na. Als je nu drie keer per uur je mail opent en dat wordt vier keer per dag, dan win je niet alleen die minuten maar ook de tijd die je kwijt bent om weer in je werk te komen. Dat is bij de meeste ondernemers een groter getal dan de mailtijd zelf, en het is precies de reden waarom dit de moeite waard is." },
      { type: "cta", text: "Wil je weten welke mailstroom bij jou als eerste te automatiseren is? Plan een vrijblijvend gesprek, dan lopen we je inbox samen door." },
    ],
  },
  {
    slug: "ai-voor-je-administratie-bonnen-facturen-uren",
    title: "AI en je administratie: bonnen, facturen en uren",
    date: "2026-07-15",
    excerpt:
      "Administratie is het werk dat je altijd vooruitschuift. Precies daarom is het het beste startpunt voor AI: het is repetitief, het heeft duidelijke regels, en je merkt direct of het scheelt.",
    readTime: "6 min",
    category: "AI & Automatisering",
    image: "/blog/ai-administratie.png",
    content: [
      { type: "intro", text: "Bonnetjes in het handschoenenkastje. Uren die je op zondagavond uit je hoofd reconstrueert. Facturen die pas de deur uitgaan als je er tijd voor hebt, wat betekent: te laat. Bijna elke ondernemer die ik spreek herkent dit, en bijna iedereen denkt dat het aan discipline ligt. Dat is meestal niet zo." },
      { type: "h2", text: "Het probleem is niet discipline, het is de drempel" },
      { type: "p", text: "Een registratie die van jou vraagt dat je eraan denkt, loopt leeg. Niet omdat je slordig bent, maar omdat het moment waarop je de gegevens hebt en het moment waarop je tijd hebt om ze in te voeren nooit samenvallen. Je krijgt de bon bij de kassa en je zit achter je administratie op donderdagavond." },
      { type: "p", text: "Dat betekent dat de oplossing niet zit in een betere herinnering, maar in het weghalen van de invoerstap. Of, als dat niet kan, in een systeem dat zelf aandraagt wat er nog mist in plaats van te wachten tot jij het bedenkt." },
      { type: "h2", text: "Wat AI hier goed kan" },
      { type: "ul", items: [
        "Een foto van een bon uitlezen: leverancier, bedrag, btw, datum, en de juiste kostenpost voorstellen",
        "Uit je agenda en je afspraken afleiden welke uren en ritten waarschijnlijk nog niet geboekt zijn",
        "Bankregels koppelen aan openstaande facturen, ook als het bedrag niet exact matcht",
        "Een factuurregel schrijven op basis van wat er in de urenregistratie staat, in plaats van uit je hoofd",
      ] },
      { type: "p", text: "Het patroon in dit lijstje: AI leest gestructureerde rommel en maakt er een voorstel van. Het is geen boekhouder en het moet ook niet doen alsof. Wat je wint is dat je van invoeren naar goedkeuren gaat, en goedkeuren doe je in seconden." },
      { type: "h2", text: "Waarom een voorstel beter is dan een automatische boeking" },
      { type: "p", text: "Bij administratie is de verleiding groot om het helemaal automatisch te maken. Weersta die. Een verkeerd geboekte uitgave vind je pas terug bij de btw-aangifte, en dan mag je drie maanden terugzoeken waar het misging. Een voorstel dat je met één klik bevestigt kost je vijf seconden en houdt je erbij." },
      { type: "p", text: "Er is een tweede reden. Zodra je zelf niet meer weet wat er in je administratie gebeurt, verlies je het gevoel voor je cijfers. En dat gevoel is precies wat je nodig hebt om te zien of een klant of een traject rendabel is." },
      { type: "h2", text: "Ook het gratis werk registreren" },
      { type: "p", text: "Een fout die veel zzp'ers maken: alleen de facturabele uren bijhouden. Klinkt logisch, want de rest lever je toch niet in rekening. Het gevolg is dat een klant waar je twintig gratis uren in hebt gestopt er in je cijfers hetzelfde uitziet als een klant waar je er nul in hebt gestopt." },
      { type: "p", text: "Boek dus alles wat je voor een klant doet, met een vinkje of het facturabel is. Dan zie je aan het eind van een traject wat het echt heeft gekost. Dat is één extra veld en het verandert hoe je naar je eigen aanbod kijkt." },
      { type: "h2", text: "Waar je begint" },
      { type: "p", text: "Neem het onderdeel waar je het meest tegenop ziet. Voor de meeste ondernemers zijn dat de bonnen, omdat die het meest verspreid binnenkomen. Zorg dat er één plek is waar een bon naartoe kan op het moment dat je hem krijgt, ook vanaf je telefoon, en laat de verwerking daarna lopen. Pas als dat een gewoonte is, ga je naar uren of facturatie." },
      { type: "cta", text: "Wil je weten welk stuk van je administratie zich het snelst laat wegnemen? Doe de gratis AI-quickscan of neem contact op." },
    ],
  },
  {
    slug: "ai-training-voor-je-team-wat-moet-erin",
    title: "Een AI-training voor je team: wat moet erin zitten?",
    date: "2026-07-19",
    excerpt:
      "Steeds meer MKB-bedrijven willen hun team meenemen in AI. Maar een training over wat AI allemaal kan, levert weinig op. Dit is wat er wel in hoort.",
    readTime: "6 min",
    category: "AI & Automatisering",
    image: "/blog/ai-training.png",
    content: [
      { type: "intro", text: "Bijna elk bedrijf dat ik spreek heeft inmiddels wel iemand op een AI-cursus gehad. En bijna elk bedrijf zegt daarna hetzelfde: leuk verhaal, maar we doen er niks mee. Dat ligt zelden aan de deelnemers en meestal aan de opzet van de training." },
      { type: "h2", text: "Waarom de meeste AI-trainingen niks veranderen" },
      { type: "p", text: "De standaardtraining laat zien wat AI allemaal kan. Tekst schrijven, samenvatten, vertalen, beelden maken, data doorzoeken. Aan het eind van de dag heeft iedereen een indrukwekkende lijst gezien en niemand weet wat hij morgenochtend anders gaat doen. Hoe groter de lijst met mogelijkheden, hoe langer mensen wachten met beginnen." },
      { type: "p", text: "Daar komt bij dat mensen in een training vaak met een voorbeeld werken dat niet van hen is. Ze schrijven een fictieve mail voor een fictief bedrijf, zien dat het werkt, en komen terug op kantoor waar het werk er heel anders uitziet." },
      { type: "h2", text: "Wat er wel in hoort" },
      { type: "ul", items: [
        "Echt eigen werk. Iedereen neemt een taak mee uit zijn eigen week, niet een voorbeeldcasus.",
        "De grenzen, expliciet. Wat mag er wel en niet in, welke gegevens blijven binnen, wie controleert wat.",
        "Waarom AI soms iets verzint, in gewone taal, zodat mensen weten wanneer ze moeten nakijken.",
        "Aan het eind één concrete afspraak per deelnemer: dit ga ik volgende week doen.",
        "Een moment een paar weken later om te kijken wat er is blijven hangen.",
      ] },
      { type: "p", text: "Dat laatste punt is waar de meeste trainingen op stuklopen. Een dag is genoeg om iets te laten zien, maar niet genoeg om een gewoonte te maken. Zonder terugkommoment zakt het weg, hoe goed de dag ook was." },
      { type: "h2", text: "Verschillende mensen hebben verschillende trainingen nodig" },
      { type: "p", text: "In een team van tien zitten meestal drie groepen. Een paar mensen zijn al bezig en willen vooral weten hoe ze het beter en veiliger doen. De grootste groep heeft het één keer geprobeerd, was niet onder de indruk, en is gestopt. En er is bijna altijd iemand die er principieel niet aan wil." },
      { type: "p", text: "Die middelste groep is waar je winst zit. Die mensen hebben geen inspiratie nodig maar een goed voorbeeld uit hun eigen werk waarin ze zien dat het wel scheelt. Richt je training daarop en de rest volgt vanzelf." },
      { type: "quote", text: "Een training is geslaagd als er de week erna iets anders gaat op kantoor. Niet als iedereen enthousiast naar huis ging." },
      { type: "h2", text: "En de kosten" },
      { type: "p", text: "Een training voor een team is een investering die je kunt terugrekenen. Als vijf mensen elk twee uur per week winnen, is dat tien uur per week. Zet daar je eigen uurtarief onder en je weet binnen hoeveel weken het eruit is. Doe die som voordat je boekt, niet erna." },
      { type: "p", text: "Er zijn ook regelingen die scholing in het MKB ondersteunen. Of jouw aanvraag daarvoor in aanmerking komt hangt af van de voorwaarden van dat moment en hoe je de aanvraag opbouwt, dus check dat altijd bij de actuele bron en niet bij een blogpost. Meer daarover staat in [SLIM-subsidie aanvragen](/blog/slim-subsidie-aanvragen)." },
      { type: "cta", text: "Denk je aan een AI-training voor je team? Kijk bij [trainingen](/trainingen) of plan een vrijblijvend gesprek, dan stemmen we de inhoud af op het werk dat jullie echt doen." },
    ],
  },
  {
    slug: "waarom-ai-projecten-in-het-mkb-stuklopen",
    title: "Waarom AI-projecten in het MKB stuklopen",
    date: "2026-07-23",
    excerpt:
      "Het gaat zelden mis op de techniek. Het gaat mis op de scope, op het eigenaarschap en op de vraag of iemand het na drie maanden nog gebruikt. Vijf patronen die ik steeds terugzie.",
    readTime: "6 min",
    category: "AI & Automatisering",
    image: "/blog/ai-stukloopt.png",
    content: [
      { type: "intro", text: "Er wordt veel geschreven over wat AI kan. Er wordt weinig geschreven over waarom het bij zoveel bedrijven na een half jaar stilligt. Dat is jammer, want dat is de kant waar je het meest van leert. Hier zijn de patronen die ik het vaakst tegenkom." },
      { type: "h2", text: "1. Te groot beginnen" },
      { type: "p", text: "Het klassieke patroon: er wordt een werkgroep opgericht, er komt een inventarisatie van alle processen, en er volgt een plan met vier fases. Zes maanden later is er nog niks in gebruik en is het enthousiasme op. Een systeem dat na twee weken één taak echt oplost, verandert meer dan een plan dat alles dekt." },
      { type: "h2", text: "2. Het probleem was er niet" },
      { type: "p", text: "Soms wordt er iets gebouwd omdat het kon, niet omdat iemand er last van had. De test is simpel: als het morgen kapot gaat, wie merkt dat dan? Kun je die vraag niet beantwoorden, dan los je geen probleem op en gaat het vanzelf stilvallen." },
      { type: "h2", text: "3. Niemand is eigenaar" },
      { type: "p", text: "Bij een pilot is iedereen betrokken. Zodra het draait is er niemand die verantwoordelijk is voor de vraag of het nog goed werkt. Dan verandert er iets in de gegevens, gaat de uitvoer stilletjes de mist in, en niemand ziet het. Twee maanden later gebruikt niemand het meer en weet niemand precies waarom." },
      { type: "p", text: "De oplossing is niet ingewikkeld. Wijs iemand aan die het gebruikt en die het mag afkeuren. Dat is geen technische rol, dat is de persoon die het werk kent." },
      { type: "h2", text: "4. Het gaat stil kapot" },
      { type: "p", text: "Software die crasht merk je. AI die geleidelijk slechtere antwoorden geeft merk je niet, want het blijft er goed uitzien. Dat is het gevaarlijkste faalpatroon van allemaal, en de reden waarom je bij dit soort systemen altijd iets moet inbouwen dat luid mag falen: een controle waar het systeem zelf zegt dat het het niet weet, in plaats van een gok met een net antwoord eromheen." },
      { type: "ul", items: [
        "Zorg dat het systeem mag zeggen dat het iets niet weet, in plaats van iets te verzinnen",
        "Houd een kleine set voorbeelden bij waarvan je het goede antwoord kent, en toets daar periodiek op",
        "Laat de uitkomsten ergens landen waar een mens ze langs ziet komen, niet in een map die niemand opent",
      ] },
      { type: "h2", text: "5. De uitzonderingen zijn niet meegenomen" },
      { type: "p", text: "Elk proces heeft uitzonderingen die niemand noemt, omdat de mensen die het werk doen ze onbewust zelf opvangen. Vraag je hoe iets werkt, dan krijg je de hoofdregel. Bouw je daarop, dan valt het systeem om op de dertig procent die daar niet in past." },
      { type: "p", text: "Daarom loop ik bij een nieuw traject altijd een aantal echte gevallen door in plaats van alleen het proces te bespreken. Niet om iemand te betrappen, maar omdat de uitzonderingen precies daar zitten waar de regel niet over gaat. Hoe die werkwijze eruitziet staat op de pagina over [mijn werkwijze](/werkwijze)." },
      { type: "quote", text: "Een proces dat je alleen kent uit de beschrijving, ken je niet. Je moet de gevallen zien waar de beschrijving niet over gaat." },
      { type: "h2", text: "Wat wel werkt" },
      { type: "p", text: "Eén taak, twee weken, een meetbaar verschil, en iemand die er eigenaar van is. Werkt het, dan bouw je uit. Werkt het niet, dan heb je twee weken verloren in plaats van een half jaar. Dat is niet spectaculair, maar het is wel de enige aanpak die ik consequent zie werken." },
      { type: "cta", text: "Loopt er bij jou iets vast, of wil je juist voorkomen dat het die kant op gaat? Neem contact op, dan kijken we er samen naar." },
    ],
  },
  {
    slug: "van-losse-prompt-naar-werkend-systeem",
    title: "Van een losse prompt naar iets dat echt draait",
    date: "2026-07-27",
    excerpt:
      "Een goede prompt is leuk voor één keer. Het verschil met een systeem dat elke week draait, zit in vier dingen die niks met prompten te maken hebben.",
    readTime: "5 min",
    category: "AI & Automatisering",
    image: "/blog/ai-prompt-naar-systeem.png",
    content: [
      { type: "intro", text: "Veel ondernemers komen op hetzelfde punt vast te zitten. Ze hebben een prompt gevonden die goed werkt, ze gebruiken hem een paar keer, en dan verwatert het. Volgende maand weten ze niet meer precies hoe ze hem hadden opgezet, en de collega die het ook zou gaan gebruiken doet het net anders. Dat is geen promptprobleem." },
      { type: "h2", text: "Het verschil tussen een prompt en een systeem" },
      { type: "p", text: "Een prompt is een instructie die jij op dat moment geeft. Een systeem is diezelfde instructie, plus de gegevens die erbij horen, plus een vaste plek waar de uitkomst landt, plus iemand die kijkt of het nog klopt. Die drie extra onderdelen zijn saai en ze zijn precies waarom het ene wel blijft draaien en het andere niet." },
      { type: "ul", items: [
        "De instructie staat ergens vast, niet in je hoofd of in een chat van vorige maand",
        "De gegevens komen er automatisch bij, in plaats van dat jij ze telkens opnieuw plakt",
        "De uitkomst gaat naar een plek waar hij gebruikt wordt: je administratie, je mail, je documentmap",
        "Er is iemand die het mag afkeuren als het niet meer klopt",
      ] },
      { type: "h2", text: "Waarom kopiëren en plakken je opbreekt" },
      { type: "p", text: "Zolang jij de gegevens er handmatig bij zet, is er een moment waarop je dat vergeet of net iets anders doet. En omdat AI netjes antwoordt op wat je geeft, krijg je dan een net antwoord op onvolledige informatie. Dat is lastiger te betrappen dan een foutmelding." },
      { type: "p", text: "Dat is ook de reden dat de meeste winst niet in een beter model zit maar in de koppeling. Zodra de klantgegevens, de tarieven of de voorraadstand automatisch meekomen, verdwijnt een hele categorie fouten in één keer." },
      { type: "h2", text: "Klein vastzetten kan al veel" },
      { type: "p", text: "Je hoeft hier geen software voor te laten bouwen. De eerste stap is meestal dat je de instructie op een vaste plek zet waar iedereen hem pakt: een custom instructie, een document in je gedeelde map, een sjabloon in het pakket dat je al gebruikt. Dat kost een middag en het haalt de grootste variatie er al uit." },
      { type: "p", text: "Pas als dat een paar weken loopt, weet je of het de moeite waard is om de gegevens automatisch aan te sluiten. En dan weet je ook precies wat er aangesloten moet worden, want dat is intussen het handwerk dat overblijft." },
      { type: "quote", text: "Bouw het pas op als het voor jou werkt. Niet andersom." },
      { type: "h2", text: "Wanneer je wel echt iets moet laten bouwen" },
      { type: "p", text: "Er is een grens. Zodra meerdere mensen het moeten gebruiken, of zodra het aan je administratie of je klantgegevens hangt, is een gedeeld document niet meer genoeg. Dan wil je dat de regels op één plek staan en dat je kunt terugzien wat er gebeurd is. Dat is het moment om er iets omheen te zetten." },
      { type: "p", text: "Het goede nieuws is dat dat tegenwoordig veel sneller gaat dan mensen denken. Waar iets bouwen vroeger weken developertijd kostte, is een werkend eerste systeem nu vaak een kwestie van dagen. Meer over hoe zo'n traject loopt lees je in [AI-automatisering: een proces, een week, meetbaar resultaat](/blog/ai-automatisering-een-proces-een-week)." },
      { type: "cta", text: "Heb je een prompt die werkt maar niet blijft hangen? Neem contact op, dan kijken we wat er nodig is om er iets van te maken dat draait." },
    ],
  },
  {
    slug: "ai-in-de-bouw-en-installatie",
    title: "AI in de bouw en installatie: waar het echt tijd bespaart",
    date: "2026-07-31",
    excerpt:
      "In de bouw en installatie zit de tijdwinst niet op de bouwplaats maar op kantoor. Werkbonnen, calculaties, tekeningen en de eeuwige zoektocht naar de laatste versie.",
    readTime: "6 min",
    category: "AI & Automatisering",
    image: "/blog/ai-bouw.png",
    content: [
      { type: "intro", text: "Als je met je handen werkt, klinkt AI al snel als iets voor kantoorbanen. Dat klopt ook, en dat is precies waarom het interessant is: in de bouw en installatie zit het papierwerk vaak in de avonduren, bovenop een volle werkdag. Daar zit de winst." },
      { type: "h2", text: "Waar de tijd echt weglekt" },
      { type: "p", text: "Vraag een installateur waar zijn week heen gaat en het antwoord is bijna nooit het werk zelf. Het zijn de calculaties, de werkbonnen die nog uitgetypt moeten worden, de foto's die bij het juiste project moeten, en de vraag welke versie van de tekening nu de laatste is. Stuk voor stuk werk dat moet gebeuren en dat niemand leuk vindt." },
      { type: "ul", items: [
        "Werkbonnen: gesproken of losse aantekeningen omzetten naar een nette regel per project",
        "Calculaties: een uitvraag omzetten naar een eerste opzet met posten, op basis van je eigen eerdere calculaties",
        "Documenten: uit een stapel tekeningen en bladen halen wat de actuele versie is en wat er veranderd is",
        "Nacalculatie: geboekte uren en materiaal naast de calculatie leggen zodat je ziet waar je eronder of erover zat",
      ] },
      { type: "h2", text: "Let op bij tekeningen en revisies" },
      { type: "p", text: "Dit is een valkuil waar ik zelf tegenaan ben gelopen. Bij een set tekeningen lijkt het logisch om de datum uit het titelblok te pakken om te bepalen wat de laatste versie is. Dat gaat mis, want dat titelblok blijft soms staan terwijl de revisieletter gewoon doorloopt. Op een set van negen bladen klopte het bij drie niet." },
      { type: "p", text: "De les is breder dan tekeningen. Als een klant zegt hoe zijn proces werkt, is dat een hypothese, geen specificatie. Mensen vatten hun eigen werkwijze samen en laten de uitzonderingen weg die ze onbewust zelf opvangen. Test een regel dus altijd op een echte set van hun eigen documenten en tel hoe vaak hij het goede antwoord geeft." },
      { type: "quote", text: "Draai de regel over een stapel van hun eigen werk. Klopt hij niet overal, dan mist de bron iets, niet de klant." },
      { type: "h2", text: "Wat er niet verandert" },
      { type: "p", text: "Het vakwerk. Wat er op de bouwplaats gebeurt, wat je ziet als je een installatie openmaakt, de inschatting of iets kan of niet: daar komt geen AI aan te pas en dat gaat de eerste jaren ook niet gebeuren. Dat is geen troostprijs maar de kern: jouw vak wordt niet minder waard als het papierwerk minder tijd kost." },
      { type: "p", text: "Meer over die scheiding tussen handwerk en papierwerk staat in [AI voor vakmensen](/blog/ai-voor-vakmensen-werk-je-met-je-handen)." },
      { type: "h2", text: "Waar je begint" },
      { type: "p", text: "Neem de klus die je in het weekend doet. Voor de meeste bedrijven in deze hoek zijn dat de werkbonnen of de calculaties. Pak je laatste tien en kijk wat er in alle tien hetzelfde is. Dat is je startpunt, en het is meteen je testset: als het daarop werkt, weet je dat je iets hebt." },
      { type: "cta", text: "Werk je in de bouw of installatie en vraag je je af waar je zou beginnen? Doe de gratis AI-quickscan of plan een gesprek, dan kijk ik mee naar hoe het nu loopt." },
    ],
  },
  {
    slug: "wat-is-een-custom-gpt",
    title: "Wat is een custom GPT en heb je er iets aan?",
    date: "2026-08-04",
    excerpt:
      "Een custom GPT is niet meer dan een chatbot met vaste instructies en je eigen documenten erbij. Simpel, goedkoop, en voor sommige taken precies genoeg. Voor andere niet.",
    readTime: "5 min",
    category: "AI & Automatisering",
    image: "/blog/ai-custom-gpt.png",
    content: [
      { type: "intro", text: "Custom GPT, project, assistent, agent: er zweven veel woorden rond voor min of meer hetzelfde idee. Namelijk: een AI die je niet elke keer opnieuw hoeft uit te leggen wat de bedoeling is. Het is een van de weinige stappen die je vandaag zelf kunt zetten zonder dat er iemand aan te pas komt." },
      { type: "h2", text: "Wat het precies is" },
      { type: "p", text: "Je neemt een gewoon taalmodel en geeft het twee dingen mee die blijven staan. Ten eerste een vaste instructie: wie het is, voor wie het schrijft, in welke toon, en wat het nooit moet doen. Ten tweede een set documenten waar het uit mag putten: je prijslijst, je voorwaarden, je productinformatie, je veelgestelde vragen." },
      { type: "p", text: "Dat is het. Er wordt niks getraind, er verandert niks aan het model. Je zet alleen de context vast zodat je hem niet elke keer opnieuw hoeft te typen. En precies dat is waarom het werkt: de meeste tijd bij AI gaat op aan opnieuw uitleggen." },
      { type: "h2", text: "Waar het goed voor is" },
      { type: "ul", items: [
        "Vragen beantwoorden over je eigen aanbod, voor jezelf of voor een collega die het niet uit zijn hoofd kent",
        "Teksten schrijven die altijd dezelfde toon en dezelfde standaardinformatie moeten hebben",
        "Nieuwe medewerkers wegwijs maken in hoe iets bij jullie werkt",
        "Een eerste opzet maken van iets dat je daarna zelf afmaakt",
      ] },
      { type: "h2", text: "Waar het niet goed voor is" },
      { type: "p", text: "Alles waar de gegevens live moeten zijn. Een custom GPT kent de documenten die je erin hebt gezet op het moment dat je ze erin zette. Vraag je naar je actuele voorraad, je openstaande facturen of de planning van volgende week, dan geeft hij een antwoord op basis van een momentopname. Dat is precies het soort fout dat er goed uitziet." },
      { type: "p", text: "Ook niet geschikt voor alles wat iets moet doen in plaats van iets moet vertellen. Een factuur aanmaken, een afspraak verzetten, een regel in je systeem wegschrijven: daar heb je een koppeling voor nodig, geen chatvenster. Dat is het verschil met een echte agent, waar meer over staat in [wat is een AI-agent](/blog/wat-is-een-ai-agent-en-wat-levert-het-op)." },
      { type: "h2", text: "Waar je op moet letten met je documenten" },
      { type: "p", text: "Zet er niets in wat je niet in een mail naar buiten zou zetten. Geen persoonsgegevens van klanten, geen contracten, geen marges die niet gedeeld mogen worden. En houd bij wat je erin hebt gezet, want over een half jaar weet je dat niet meer en dan kun je ook niet meer beoordelen of een antwoord op oude informatie is gebaseerd." },
      { type: "p", text: "Zet er ook een datum bij in de instructie, bijvoorbeeld dat de prijslijst van een bepaalde maand is. Dan kan het zelf zeggen dat de informatie mogelijk verouderd is in plaats van hem als actueel te presenteren." },
      { type: "h2", text: "Een goede eerste stap" },
      { type: "p", text: "Van alle dingen die je met AI kunt doen, is dit de goedkoopste manier om te ontdekken of het bij jou iets oplevert. Je bouwt niks, je koppelt niks, en je bent binnen een uur klaar. Werkt het, dan weet je waar de winst zit en kun je overwegen om het steviger vast te zetten. Werkt het niet, dan heb je een uur besteed in plaats van een project gestart." },
      { type: "cta", text: "Wil je weten of een custom GPT voor jouw werk genoeg is, of dat je iets steviger nodig hebt? Doe de gratis AI-quickscan of neem contact op." },
    ],
  },
  {
    slug: "ai-voor-je-klantenservice",
    title: "AI in je klantenservice zonder dat het onpersoonlijk wordt",
    date: "2026-08-08",
    excerpt:
      "Een chatbot die je klant het bos in stuurt kost je meer dan hij oplevert. Toch is klantenservice een van de plekken waar AI het meeste scheelt, mits je het op de juiste plek zet.",
    readTime: "5 min",
    category: "AI & Automatisering",
    image: "/blog/ai-klantenservice.png",
    content: [
      { type: "intro", text: "Iedereen kent het gevoel: je hebt een vraag, je krijgt een chatvenster, en na vier keer heen en weer typen zoek je naar het telefoonnummer. Dat is de reden waarom veel ondernemers hun handen niet aan AI in de klantenservice willen branden. Terecht, als je het zo doet." },
      { type: "h2", text: "De fout die iedereen maakt" },
      { type: "p", text: "De standaardaanpak is: zet een bot voor de deur en laat die zoveel mogelijk vragen afvangen. Het doel wordt dan het aantal afgevangen gesprekken, en dat is precies het verkeerde doel. Een klant die is afgevangen zonder antwoord, is een klant die vertrekt of die alsnog belt, maar dan geïrriteerd." },
      { type: "p", text: "Het betere doel is: zorgen dat de vraag sneller bij het goede antwoord komt. Soms is dat een bot, vaak is dat een mens die beter voorbereid is." },
      { type: "h2", text: "Zet AI achter de deur, niet ervoor" },
      { type: "p", text: "De meeste winst zit aan jouw kant van het gesprek. Als een vraag binnenkomt, kan AI in seconden ophalen wat er eerder met deze klant is besproken, wat er in de voorwaarden staat en wat het standaardantwoord op dit type vraag is. Jouw medewerker begint dan niet bij nul maar bij een concept." },
      { type: "ul", items: [
        "De vraag wordt gesorteerd, zodat urgente dingen niet onderin blijven liggen",
        "De geschiedenis met deze klant staat er direct bij, zonder dat iemand hoeft te zoeken",
        "Er ligt een conceptantwoord klaar in jullie eigen toon, met de juiste informatie erbij",
        "Een mens leest het na, past aan en verstuurt",
      ] },
      { type: "p", text: "Voor de klant verandert er niets aan hoe persoonlijk het voelt. Voor jou halveert de tijd per vraag. Dat is een betere ruil dan een bot die aan de voorkant staat te raden." },
      { type: "h2", text: "Wanneer een bot aan de voorkant wel kan" },
      { type: "p", text: "Er is één situatie waarin het wel werkt: als het antwoord echt vaststaat en de klant er meteen iets aan heeft. Openingstijden, de status van een bestelling, waar iets te vinden is op je site. Feiten dus, geen oordelen. Zorg dan wel dat er altijd binnen één stap een mens bereikbaar is, zonder dat de klant daarvoor moet zoeken." },
      { type: "p", text: "Alles wat met geld, klachten of uitzonderingen te maken heeft, laat je met rust. Daar is de toon de inhoud, en dat is niet iets waar je een systeem verantwoordelijk voor wilt maken." },
      { type: "quote", text: "Meet niet hoeveel vragen je hebt afgevangen. Meet hoeveel vragen in één keer goed beantwoord zijn." },
      { type: "h2", text: "En de privacy" },
      { type: "p", text: "Klantvragen bevatten bijna altijd persoonsgegevens. Kies dus een opzet waarbij die gegevens niet zomaar bij een willekeurige dienst terechtkomen, en leg vast wie waar bij kan. Dat is geen formaliteit: het is het onderdeel waar je later spijt van krijgt als je het overslaat. Meer daarover in [AI en privacy of AVG](/blog/ai-en-avg-waar-moet-mkb-op-letten)." },
      { type: "cta", text: "Wil je kijken wat er in jouw klantcontact te winnen valt zonder dat het onpersoonlijk wordt? Neem contact op." },
    ],
  },
  {
    slug: "je-eigen-documenten-aan-ai-koppelen",
    title: "Je eigen documenten aan AI koppelen: zo werkt dat",
    date: "2026-08-12",
    excerpt:
      "AI die je eigen handleidingen, contracten en prijslijsten kent, is voor veel bedrijven de eerste toepassing die echt iets oplevert. Zo werkt het, in gewone taal.",
    readTime: "6 min",
    category: "AI & Automatisering",
    image: "/blog/ai-eigen-documenten.png",
    content: [
      { type: "intro", text: "Een taalmodel weet veel over de wereld en niets over jouw bedrijf. Het kent je prijzen niet, je voorwaarden niet en je handleidingen niet. Zodra je dat oplost, verandert het van een handige tekstschrijver in iets dat vragen over jouw werk kan beantwoorden. Dat is voor de meeste MKB-bedrijven de eerste stap die echt iets oplevert." },
      { type: "h2", text: "Hoe het werkt zonder jargon" },
      { type: "p", text: "Je documenten worden in stukken geknipt en zo opgeslagen dat er op betekenis gezocht kan worden, niet alleen op letterlijke woorden. Stelt iemand een vraag, dan worden eerst de paar stukken opgezocht die daarover gaan, en die worden aan het model meegegeven. Het antwoord komt dus uit jouw documenten, niet uit het geheugen van het model." },
      { type: "p", text: "Dat is meteen de reden waarom dit betrouwbaarder is dan een model gewoon iets vragen. Het model hoeft niet te onthouden, het hoeft alleen te lezen wat je erbij levert. En je kunt laten tonen uit welk document het antwoord komt, zodat je het kunt nakijken." },
      { type: "h2", text: "Waar het goed voor is" },
      { type: "ul", items: [
        "Handleidingen en technische documentatie waar niemand alles van uit zijn hoofd kent",
        "Contracten en voorwaarden: wat staat er precies over aansprakelijkheid, opzegtermijn of levertijd",
        "Interne procedures, zodat nieuwe mensen niet elke keer iemand hoeven te vragen",
        "Historisch materiaal: eerdere offertes, projectdossiers, verslagen",
      ] },
      { type: "h2", text: "De valkuil: rommel erin is rommel eruit" },
      { type: "p", text: "Dit is waar het bij de meeste bedrijven misgaat. Als je vier versies van dezelfde prijslijst in je mappen hebt staan, dan komen die er alle vier in en dan kiest het systeem er willekeurig een. Het antwoord ziet er dan prima uit en klopt niet. Dat is een pijnlijker soort fout dan een foutmelding." },
      { type: "p", text: "Neem daarom vooraf de tijd om te bepalen welke versie de geldende is. Dat is saai werk en het is het belangrijkste onderdeel van het hele project. Reken erop dat het opruimen van de documenten meer tijd kost dan het aansluiten ervan." },
      { type: "quote", text: "Een systeem dat op oude documenten draait, geeft nette antwoorden die niet kloppen. Dat is erger dan geen systeem." },
      { type: "h2", text: "Wat je moet regelen voordat je begint" },
      { type: "p", text: "Drie dingen. Wie mag wat zien, want niet elke medewerker hoeft bij de contracten te kunnen. Waar staan de gegevens, want dat bepaalt of je aan je eigen privacybeleid voldoet. En wie houdt bij dat de bron actueel blijft, want zonder eigenaar veroudert het binnen een half jaar zonder dat iemand het merkt." },
      { type: "p", text: "Dat derde punt is dezelfde valkuil als bij elk AI-project: het gaat stil kapot. Zet daarom een vast moment in de agenda waarop iemand controleert of de gebruikte documenten nog de juiste zijn." },
      { type: "h2", text: "Klein beginnen kan hier ook" },
      { type: "p", text: "Je hoeft niet je hele documentarchief aan te sluiten. Begin met de tien documenten waar de meeste vragen over gaan. Dat is bij de meeste bedrijven genoeg om te zien of het werkt, en het is klein genoeg om ze eerst goed op te ruimen. Werkt het, dan breid je uit met de volgende tien." },
      { type: "cta", text: "Wil je weten welke documenten bij jou de meeste vragen opleveren? Doe de gratis AI-quickscan of plan een gesprek." },
    ],
  },
  {
    slug: "ai-voor-planning-en-logistiek",
    title: "AI voor planning en logistiek in het MKB",
    date: "2026-08-16",
    excerpt:
      "Planning is het werk waar iedereen last van heeft en niemand eigenaar van is. AI lost het niet op, maar het haalt er wel het zoekwerk en het bellen uit.",
    readTime: "5 min",
    category: "AI & Automatisering",
    image: "/blog/ai-planning.png",
    content: [
      { type: "intro", text: "Planning is bij de meeste MKB-bedrijven het werk dat tussen alles door gebeurt. Iemand belt af, een levering schuift, en dan gaat er een half uur op aan bellen en schuiven. Het is zelden iemands functie en het kost iedereen tijd." },
      { type: "h2", text: "Het echte probleem is niet plannen, het is doorgeven" },
      { type: "p", text: "Als je meekijkt bij een planningsdag, zie je dat het schuiven zelf niet het meeste werk is. Het meeste werk is uitzoeken wat er precies aan de hand is, wie het moet weten en wat de gevolgen zijn verderop. Een levering die een dag opschuift raakt drie andere afspraken, en die drie moeten allemaal een bericht krijgen." },
      { type: "p", text: "Daar zit de winst. Niet in een algoritme dat de optimale planning berekent, maar in het wegnemen van het uitzoekwerk en het doorgeven." },
      { type: "h2", text: "Wat er concreet kan" },
      { type: "ul", items: [
        "Een wijziging binnenkrijgen en direct laten zien welke afspraken daardoor raken",
        "Berichten klaarzetten voor iedereen die het moet weten, in jullie eigen toon, klaar om te versturen",
        "Uit je eigen historie afleiden hoe lang een klus meestal echt duurt in plaats van hoe lang je hem inplant",
        "Signaleren wat er ontbreekt: een afspraak zonder monteur, een levering zonder bevestiging",
      ] },
      { type: "p", text: "Vooral dat derde punt wordt onderschat. In bijna elk bedrijf staat er in de planning een standaardduur die niemand ooit heeft nagerekend. Leg je de geplande tijd naast de werkelijk geboekte uren, dan zie je binnen een uur waar je structureel te krap of te ruim zit." },
      { type: "h2", text: "Begin met meten, niet met plannen" },
      { type: "p", text: "De verleiding is groot om meteen een slimme planner te willen. Doe dat niet. Begin met het naast elkaar leggen van wat je plande en wat het werd, over een half jaar aan gegevens. Dat kost een dag en het levert vaak meteen een paar besluiten op die niks met AI te maken hebben." },
      { type: "p", text: "Pas als je weet waar de afwijkingen zitten, heeft het zin om er iets omheen te bouwen. Anders automatiseer je een planning waarvan de uitgangspunten niet kloppen, en dan word je alleen sneller verkeerd." },
      { type: "quote", text: "Een planning die je nooit hebt teruggemeten, is een aanname met een tijdstip erbij." },
      { type: "h2", text: "Houd de mens aan de knop" },
      { type: "p", text: "Bij planning is de verleiding om het systeem zelf te laten schuiven het grootst, want dat scheelt het meest. Toch is dit een van de plekken waar ik dat afraad. Er zitten altijd afwegingen in die nergens staan opgeschreven: deze klant kun je niet nog een keer verzetten, die monteur wil je niet op dat adres. Laat het systeem voorstellen doen en laat een mens bevestigen." },
      { type: "p", text: "Dat kost een paar seconden per wijziging en het voorkomt precies het soort fout waar je klanten mee kwijtraakt." },
      { type: "cta", text: "Loopt planning bij jou ook tussendoor? Neem contact op, dan kijk ik mee naar waar het zoekwerk zit." },
    ],
  },
  {
    slug: "wat-is-een-uur-tijdwinst-waard",
    title: "Wat is een uur tijdwinst waard? AI doorrekenen voor je bedrijf",
    date: "2026-08-20",
    excerpt:
      "Iedereen roept dat AI tijd bespaart, bijna niemand rekent het na. Zonder die som weet je niet of een investering slim is of gewoon leuk.",
    readTime: "5 min",
    category: "AI & Automatisering",
    image: "/blog/ai-tijdwinst.png",
    content: [
      { type: "intro", text: "Als iemand je vertelt dat AI je twintig procent tijd bespaart, vraag dan waar dat getal vandaan komt. Meestal is het antwoord: uit een onderzoek van een partij die AI verkoopt. Dat zegt niets over jouw bedrijf. De enige som die telt is die van jouw eigen week." },
      { type: "h2", text: "De som is simpeler dan je denkt" },
      { type: "p", text: "Je hebt drie getallen nodig. Hoe vaak doe je die taak per week. Hoe lang duurt hij nu echt, gemeten en niet geschat. En hoe lang duurt hij straks, inclusief de tijd die je kwijt bent aan controleren. Dat verschil maal de frequentie is je winst per week." },
      { type: "p", text: "Zet daar je eigen uurtarief onder, of het uurtarief van degene die het werk doet. Vergelijk dat met wat het kost om het op te zetten en te onderhouden. Dan weet je binnen hoeveel weken het eruit is en of dat een termijn is waar jij mee kunt leven." },
      { type: "h2", text: "Waar de som fout gaat" },
      { type: "ul", items: [
        "Je gebruikt een geschatte tijd in plaats van een gemeten tijd. Mensen onderschatten repetitief werk consequent.",
        "Je vergeet de controletijd. Een concept nakijken kost ook minuten, en die moeten in de som.",
        "Je rekent alleen de opzetkosten en niet het onderhoud. Er moet iemand naar blijven kijken.",
        "Je telt tijdwinst als geld terwijl je die uren niet vult. Een uur minder administratie is alleen geld waard als je dat uur aan iets anders besteedt.",
      ] },
      { type: "p", text: "Vooral dat laatste punt is belangrijk en wordt bijna nooit genoemd. Als je een uur per week wint en dat uur gaat op aan koffie, dan heb je geen geld verdiend maar een rustiger week. Dat mag een prima reden zijn, maar noem het dan ook zo en verkoop het niet aan jezelf als rendement." },
      { type: "h2", text: "Meet eerst een week" },
      { type: "p", text: "Voordat je iets aanschaft of laat bouwen: houd één week bij hoe lang de taak echt duurt. Niet met een stopwatch, gewoon een streepje en een schatting per keer. Bij bijna iedereen valt dat getal hoger uit dan verwacht, en dat is precies de informatie die je nodig hebt om een goede beslissing te nemen." },
      { type: "p", text: "Diezelfde meting is later je bewijs. Als je na drie maanden wilt weten of het heeft gewerkt, wil je iets hebben om mee te vergelijken. Zonder nulmeting is elke conclusie achteraf een gevoel." },
      { type: "quote", text: "Een gok met een getal ervoor is geen meting. Schrijf op wat je niet gemeten hebt." },
      { type: "h2", text: "En als het niet uit kan" },
      { type: "p", text: "Dan doe je het niet. Dat is een prima uitkomst en het gebeurt vaker dan je denkt. Een taak die je vier keer per jaar doet, is geen automatiseringskandidaat, hoe irritant hij ook is. Dat eerlijk kunnen zeggen is precies waarom je de som maakt." },
      { type: "p", text: "Meer over wat AI in de praktijk kost lees je in [wat kost AI voor een MKB-bedrijf](/blog/wat-kost-ai-voor-een-mkb-bedrijf)." },
      { type: "cta", text: "Wil je die som samen maken voor een taak in jouw bedrijf? Plan een vrijblijvend gesprek, dan rekenen we het gewoon door." },
    ],
  },
  {
    slug: "ai-die-je-al-betaalt-microsoft-365-google-workspace",
    title: "De AI die je al betaalt: Microsoft 365 en Google Workspace",
    date: "2026-08-24",
    excerpt:
      "Voordat je een nieuw abonnement afsluit: er zit waarschijnlijk al AI in het pakket dat je maandelijks betaalt. Wat je daarmee kunt en waar het ophoudt.",
    readTime: "5 min",
    category: "AI & Automatisering",
    image: "/blog/ai-al-betaalt.png",
    content: [
      { type: "intro", text: "Een van de eerste dingen die ik doe als ik bij een bedrijf binnenkom, is kijken wat er al in huis is. Bijna altijd betaalt men al voor Microsoft 365 of Google Workspace, en bijna altijd wordt de AI die daarin zit niet gebruikt. Dat is de goedkoopste winst die er is." },
      { type: "h2", text: "Waarom dit het startpunt is" },
      { type: "p", text: "Niet omdat het de beste AI is, want dat is het meestal niet. Wel omdat het er al staat, omdat je gegevens er al in zitten en omdat je geen nieuwe leverancier, nieuw contract of nieuwe privacydiscussie nodig hebt. Voor een eerste stap weegt dat zwaarder dan de laatste procenten kwaliteit." },
      { type: "p", text: "Er zit nog een voordeel aan. Omdat het in je bestaande omgeving draait, valt het onder de afspraken die je daar al voor hebt gemaakt over waar je gegevens staan en wie erbij kan. Dat scheelt een hoop uitzoekwerk vergeleken met een losse tool waar iemand even een account voor aanmaakt." },
      { type: "h2", text: "Wat er in de praktijk goed werkt" },
      { type: "ul", items: [
        "Samenvatten van lange mailwisselingen en documenten waar je halverwege instapt",
        "Een verslag maken van een online overleg, met de actiepunten eruit",
        "Een eerste opzet van een document of presentatie op basis van bestaande stukken",
        "Zoeken door je eigen mappen en mail op betekenis in plaats van op exacte woorden",
      ] },
      { type: "h2", text: "Waar het ophoudt" },
      { type: "p", text: "Zodra je iets specifieks wilt dat elke keer op dezelfde manier moet, loop je tegen de grens aan. Deze assistenten zijn breed en algemeen, en dat is precies waarom ze voor jouw specifieke offerteproces of jouw manier van calculeren net niet goed genoeg zijn. Ze weten niet hoe jij het doet." },
      { type: "p", text: "Ook voor schrijfwerk waar toon echt telt, merken de meeste mensen verschil met de gespecialiseerde modellen. Dat betekent niet dat je moet overstappen, wel dat je moet weten waarvoor je wat gebruikt. Meer daarover in [multi-model werken](/blog/multi-llm-werken)." },
      { type: "h2", text: "Kijk eerst, koop daarna" },
      { type: "p", text: "Voordat je licenties uitbreidt: check wat er in jullie huidige abonnement zit en of het aanstaat. Bij veel bedrijven staat de functionaliteit uit omdat niemand hem heeft aangezet, of hij staat aan en niemand weet het. Een half uur in de beheeromgeving levert vaak meer op dan een nieuwe aanschaf." },
      { type: "p", text: "En als je daarna alsnog een aparte tool nodig hebt, weet je tenminste precies waarvoor. Dat is een veel beter gesprek met je leverancier dan beginnen bij nul." },
      { type: "cta", text: "Wil je weten wat er in jouw huidige pakket al zit? Doe de gratis AI-quickscan, dan zie je meteen waar je begint." },
    ],
  },
  {
    slug: "ai-en-je-personeel-verdwijnt-er-werk",
    title: "AI en je personeel: verdwijnt er werk of verandert het?",
    date: "2026-08-28",
    excerpt:
      "De vraag die elke ondernemer stelt en bijna niemand hardop. Het eerlijke antwoord is genuanceerder dan zowel de doemverhalen als de verkooppraatjes.",
    readTime: "6 min",
    category: "AI & Automatisering",
    image: "/blog/ai-personeel.png",
    content: [
      { type: "intro", text: "Als ik bij een bedrijf zit, komt deze vraag bijna altijd. Soms van de ondernemer, vaker van iemand op de werkvloer, en meestal pas als de rest van de kamer leeg is. Het verdient een eerlijk antwoord en niet het standaardzinnetje dat AI alleen maar helpt." },
      { type: "h2", text: "Wat er echt gebeurt" },
      { type: "p", text: "In het MKB zie ik zelden dat er banen verdwijnen. Wat ik wel zie is dat er taken verdwijnen, en dat is iets anders. Van de meeste functies is een deel van het werk repetitief invoerwerk, en dat deel wordt kleiner. Wat overblijft is het werk waar oordeel bij komt kijken, en daar was meestal al te weinig tijd voor." },
      { type: "p", text: "Het praktische gevolg is meestal niet minder mensen maar meer werk aan dezelfde bezetting. Voor een bedrijf dat moeilijk aan personeel komt, en dat zijn er nogal wat, is dat precies de reden om ermee te beginnen." },
      { type: "h2", text: "Waar het wel spannend wordt" },
      { type: "p", text: "Er is een categorie functies die grotendeels uit invoerwerk bestaat. Gegevens overtypen, documenten sorteren, standaardberichten versturen. Als dat het grootste deel van iemands dag is, dan verandert die functie ingrijpend. Doen alsof dat niet zo is, is oneerlijk tegenover die persoon." },
      { type: "p", text: "Het goede nieuws is dat dat zelden van de ene op de andere dag gaat en dat je er als werkgever iets aan kunt doen. Iemand die het werk kent, is namelijk vaak de beste persoon om te beoordelen of het systeem het goed doet. Dat is een echte rol en geen bezigheidstherapie." },
      { type: "h2", text: "Hoe je het gesprek voert" },
      { type: "ul", items: [
        "Wees eerlijk over wat er verandert. Mensen ruiken een verkooppraatje van kilometers afstand.",
        "Begin bij het werk waar mensen zelf een hekel aan hebben, niet bij het werk waar ze trots op zijn.",
        "Laat degene die het werk doet meebeslissen over of het systeem goed genoeg is, en geef hem het recht om nee te zeggen.",
        "Zeg wat je met de gewonnen tijd gaat doen, voordat iemand het je vraagt.",
      ] },
      { type: "p", text: "Die derde is de belangrijkste. Een systeem dat over iemands hoofd heen wordt ingevoerd, wordt niet gebruikt. Een systeem dat diegene zelf heeft mogen afkeuren tot het klopte, wordt zijn systeem." },
      { type: "quote", text: "Wie het werk doet, moet het systeem mogen afkeuren. Anders is het niet van hem en gebruikt hij het niet." },
      { type: "h2", text: "Wat het voor jou als werkgever betekent" },
      { type: "p", text: "Reken er niet op dat je snel op loonkosten bespaart. Dat gebeurt in het MKB bijna nooit, en als je daarop stuurt gaat het meestal mis. Waar je wel op kunt sturen is de doorlooptijd, de foutkans en de vraag of het werk nog rond te krijgen is als iemand ziek is." },
      { type: "p", text: "Dat is een minder spannend verhaal dan wat je in de krant leest, en het is wel het verhaal dat klopt voor bedrijven van tien tot honderd man." },
      { type: "cta", text: "Wil je dit gesprek in je eigen team voeren en weet je niet waar te beginnen? Kijk bij [trainingen](/trainingen) of neem contact op." },
    ],
  },
  {
    slug: "passief-inkomen-website-google-adsense",
    title: "Passief inkomen met je website: wat Google AdSense echt oplevert",
    date: "2026-09-01",
    excerpt:
      "Advertenties op je site zijn de meest passieve verdienvorm die er is: aanmelden, code plakken, klaar. De vraag is alleen of het genoeg oplevert om het te doen. Ik heb het doorgerekend.",
    readTime: "6 min",
    category: "AI & Automatisering",
    image: "/blog/ai-adsense.png",
    content: [
      { type: "intro", text: "Er zijn veel manieren om passief inkomen op te bouwen, maar advertenties via Google AdSense is echt de meest passieve die er is. Je meldt je aan, je plakt een stukje code op je site, en vanaf dat moment worden er automatisch advertenties getoond die bij je bezoekers passen. Je hoeft geen adverteerders te benaderen, de metingen lopen vanzelf en de uitbetaling ook. Passiever wordt het niet. En toch raad ik het de meeste ondernemers af. Hieronder waarom, en wat dan wel." },
      { type: "h2", text: "Hoe het werkt en wat je moet weten" },
      { type: "p", text: "De praktische kant is inderdaad simpel, maar er zitten twee dingen aan vast die mensen verrassen." },
      { type: "ul", items: [
        "Zorg dat er minstens vijftien artikelen met echte inhoud op je site staan voordat je een account aanvraagt. Sites met weinig of dunne content komen niet door de goedkeuring.",
        "Het systeem heeft tijd nodig om te leren welke advertenties bij jouw onderwerp en jouw bezoekers passen. In de eerste maanden valt de opbrengst daardoor vaak tegen, en daarna kruipt hij langzaam omhoog.",
      ] },
      { type: "p", text: "Beide punten kloppen en beide zijn geen probleem. Het probleem zit in de derde vraag die er zelden bij gesteld wordt: wat levert het op per bezoeker, en heb jij genoeg bezoekers." },
      { type: "h2", text: "De rekensom die niemand maakt" },
      { type: "p", text: "Advertentie-inkomsten reken je per duizend paginaweergaven. Voor een Nederlandse zakelijke site praat je over een bedrag in de orde van een paar euro per duizend weergaven. Het exacte getal verschilt sterk per onderwerp en per seizoen, dus zie dit als een orde van grootte en niet als een belofte." },
      { type: "p", text: "Stel dat je site vijfduizend paginaweergaven per maand haalt, wat voor een MKB-site in Nederland al netjes is. Dan zit je in de orde van twintig euro per maand. Wil je er tweehonderdvijftig euro per maand mee verdienen, dan heb je grofweg vijftigduizend weergaven per maand nodig. Dat is een fulltime contentoperatie, geen passief inkomen." },
      { type: "quote", text: "Passief betekent dat het geld binnenkomt zonder werk. Het betekent niet dat het er komt zonder publiek." },
      { type: "h2", text: "En de verborgen kosten" },
      { type: "p", text: "Nu de kant die de meeste artikelen over dit onderwerp weglaten. Als je site bedoeld is om klanten te krijgen, dan kosten advertenties je meer dan ze opleveren. Een bezoeker die op het punt staat contact met je op te nemen, ziet nu eerst een banner voor een willekeurig product. Dat kost je vertrouwen, het maakt je site trager, en trager laadt slechter in Google." },
      { type: "p", text: "Reken het eens andersom door. Als één klant je duizend euro oplevert, dan hoeft die banner maar één keer per jaar iemand te laten afhaken om je hele advertentie-inkomsten weg te vagen. Dat is een slechte weddenschap, en het is de reden dat je op zakelijke sites die serieus klanten willen werven bijna nooit advertenties ziet." },
      { type: "h2", text: "Wanneer het wel logisch is" },
      { type: "p", text: "AdSense werkt als de site zelf het product is. Dus een aparte contentsite over een onderwerp met veel zoekvolume, waar je niks anders verkoopt en waar bezoekers geen klant hoeven te worden. Houd dat dan ook echt gescheiden van je bedrijfssite, zowel qua domein als qua doel. Dan is de afweging schoon en kun je op volume sturen zonder je merk te beschadigen." },
      { type: "h2", text: "Wat wel passief inkomen oplevert voor een MKB-bedrijf" },
      { type: "p", text: "Er zijn drie vormen die in dezelfde categorie vallen en die wel bij een zakelijke site passen, omdat ze meeliften op het vertrouwen dat je site al opbouwt in plaats van het op te eten." },
      { type: "ul", items: [
        "Een eigen digitaal product: een cursus, een sjablonenpakket of een werkboek dat je één keer maakt en daarna blijft verkopen. De marge is hoog en het versterkt je positionering in plaats van hem te verwateren.",
        "Aanbevelingen van gereedschap dat je echt gebruikt, met een affiliate-link erbij. Eén doorverwijzing naar een tool die iemand jaren gebruikt, levert meer op dan duizenden banner-vertoningen. Voorwaarde: je noemt het gewoon, en je beveelt niks aan dat je zelf niet zou nemen.",
        "Een betaald hulpmiddel op je eigen site: een scan, een rekentool of een generator die klein genoeg is om zelfstandig te draaien. Dat is niet honderd procent passief, maar het schaalt wel en het levert je meteen klanten op.",
      ] },
      { type: "p", text: "Het patroon in alle drie: je verkoopt iets dat past bij waar je site over gaat. Daarmee versterkt de ene inkomstenbron de andere, terwijl advertenties precies het omgekeerde doen." },
      { type: "h2", text: "En AI dan" },
      { type: "p", text: "De verleiding is groot om AI honderden artikelen te laten schrijven en zo aan het benodigde volume te komen. Doe dat niet. Google is er de laatste jaren steeds beter in geworden om massaal geproduceerde content te herkennen, en de sites die op die manier omhoog schoten zijn ook weer even hard gezakt. Bovendien komt zo'n site niet door de goedkeuring die hierboven genoemd staat." },
      { type: "p", text: "Waar AI wel bij helpt: sneller een goed artikel maken over iets waar jij verstand van hebt. Onderzoek, structuur, een eerste opzet, en jij maakt het af met wat jij weet en niemand anders. Dat is een vermenigvuldiger op jouw kennis en geen vervanging ervan. Hoe je dat doet zonder je eigen stem kwijt te raken staat in [samenwerken met AI zonder je eigen stem te verliezen](/blog/ai-en-eigen-schrijfstijl)." },
      { type: "cta", text: "Denk je na over een digitaal product of een tool op je eigen site? Neem contact op, dan kijken we samen wat er past bij wat je nu al doet." },
    ],
  },
];
